'''
Python dictionary listing possible tags within a Matroska file

EBML specification from https://raw.githubusercontent.com/ietf-wg-cellar/ebml-specification/refs/heads/master/ebml.xml 
Matroska specification from https://raw.githubusercontent.com/ietf-wg-cellar/matroska-specification/refs/heads/master/ebml_matroska.xml

An XSLT 2.0 transform mkv.xsl is applied to the EBML and Matroska specification files.

Output of transformations is merged and manipulated by ./create_lookup.sh to produce idlookups.py
'''
id_table = {
  0x1A45DFA3: {'name': 'EBML',
    'type': 'master',
    'level': 0,
    'documentation': 'definition:- Set the EBML characteristics of the data to follow. Each EBML document has to start with this.\n'},
  0x4286: {'name': 'EBMLVersion',
    'type': 'uinteger',
    'level': 1,
    'default': '1',
    'documentation': 'definition:- The version of EBML parser used to create the file.\n'},
  0x42F7: {'name': 'EBMLReadVersion',
    'type': 'uinteger',
    'level': 1,
    'default': '1',
    'documentation': 'definition:- The minimum EBML version a parser has to support to read this file.\n'},
  0x42F2: {'name': 'EBMLMaxIDLength',
    'type': 'uinteger',
    'level': 1,
    'default': '4',
    'documentation': 'definition:- The maximum length of the IDs you''ll find in this file (4 or less in Matroska).\n'},
  0x42F3: {'name': 'EBMLMaxSizeLength',
    'type': 'uinteger',
    'level': 1,
    'default': '8',
    'documentation': 'definition:- The maximum length of the sizes you''ll find in this file (8 or less in Matroska). This does not override the element size indicated at the beginning of an element. Elements that have an indicated size which is larger than what is allowed by EBMLMaxSizeLength shall be considered invalid.\n'},
  0x4282: {'name': 'DocType',
    'type': 'string',
    'level': 1,
    'documentation': 'definition:- A string that describes the type of document that follows this EBML header, for example ''matroska'' or ''webm''.\n'},
  0x4287: {'name': 'DocTypeVersion',
    'type': 'uinteger',
    'level': 1,
    'default': '1',
    'documentation': 'definition:- The version of DocType interpreter used to create the file.\n'},
  0x4285: {'name': 'DocTypeReadVersion',
    'type': 'uinteger',
    'level': 1,
    'default': '1',
    'documentation': 'definition:- The minimum DocType version an interpreter has to support to read this file.\n'},
  0x4281: {'name': 'DocTypeExtension',
    'type': 'master',
    'level': 1,
    'documentation': 'definition:- A DocTypeExtension adds extra Elements to the main DocType+DocTypeVersion	tuple it''s attached to. An EBML Reader **MAY** know these extra Elements and how to use them. A DocTypeExtension **MAY** be used to iterate between	experimental Elements before they are integrated into a regular	DocTypeVersion. Reading one DocTypeExtension version of a DocType+DocTypeVersion tuple doesn''t imply one should be able to read upper versions of this DocTypeExtension.\n'},
  0x4283: {'name': 'DocTypeExtensionName',
    'type': 'string',
    'level': 2,
    'documentation': 'definition:- The name of the DocTypeExtension to differentiate it from other DocTypeExtensions of the same DocType+DocTypeVersion tuple. A DocTypeExtensionName value **MUST** be unique within the EBML Header.\n'},
  0x4284: {'name': 'DocTypeExtensionVersion',
    'type': 'uinteger',
    'level': 2,
    'documentation': 'definition:- The version of the DocTypeExtension. Different DocTypeExtensionVersion values of the same DocType + DocTypeVersion + DocTypeExtensionName tuple **MAY** contain completely different sets of extra Elements. An EBML Reader **MAY** support multiple versions	of the same tuple, only one version of the tuple, or not support the tuple at all.\n'},
  0xEC: {'name': 'Void',
    'type': 'binary',
    'level': 7,
    'documentation': 'definition:- Used to void damaged data, to avoid unexpected behaviors when using damaged data. The content is discarded. Also used to reserve space in a sub-element for later use.\n'},
  0xBF: {'name': 'CRC-32',
    'type': 'binary',
    'level': 7,
    'documentation': 'definition:- The CRC is computed on all the data of the Master element it''s in. The CRC element should be the first in it''s parent master for easier reading. All level 1 elements should include a CRC-32. The CRC in use is the IEEE CRC32 Little Endian.\n'},
  0x42F2: {'name': 'EBMLMaxIDLength',
    'type': 'uinteger',
    'level': 1,
    'default': '4',
    'documentation': ''},
  0x42F3: {'name': 'EBMLMaxSizeLength',
    'type': 'uinteger',
    'level': 1,
    'default': '8',
    'documentation': ''},
  0x18538067: {'name': 'Segment',
    'type': 'master',
    'level': 0,
    'documentation': 'definition:- The `Root Element` that contains all other `Top-Level Elements`; see (#data-layout).\n'},
  0x114D9B74: {'name': 'SeekHead',
    'type': 'master',
    'level': 1,
    'documentation': 'definition:- Contains seeking information of `Top-Level Elements`; see (#data-layout).\n'},
  0x4DBB: {'name': 'Seek',
    'type': 'master',
    'level': 2,
    'documentation': 'definition:- Contains a single seek entry to an EBML Element.\n'},
  0x53AB: {'name': 'SeekID',
    'type': 'binary',
    'level': 3,
    'documentation': 'definition:- The binary EBML ID of a `Top-Level Element`.\n'},
  0x53AC: {'name': 'SeekPosition',
    'type': 'uinteger',
    'level': 3,
    'documentation': 'definition:- The `Segment Position` ((#segment-position)) of a `Top-Level Element`.\n'},
  0x1549A966: {'name': 'Info',
    'type': 'master',
    'level': 1,
    'documentation': 'definition:- Contains general information about the `Segment`.\n'},
  0x73A4: {'name': 'SegmentUUID',
    'type': 'binary',
    'level': 2,
    'documentation': 'definition:- A randomly generated UID that identifies the `Segment` amongst many others (128 bits). It is equivalent to a Universally Unique Identifier (UUID) v4 [@!RFC9562] with all bits randomly (or pseudorandomly) chosen.  An actual UUID v4 value, where some bits are not random, **MAY** also be used.\nusage notes:- If the `Segment` is a part of a `Linked Segment`, then this element is **REQUIRED**.\nThe value of the UID **MUST** contain at least one bit set to 1.\n'},
  0x7384: {'name': 'SegmentFilename',
    'type': 'utf-8',
    'level': 2,
    'documentation': 'definition:- A filename corresponding to this `Segment`.\n'},
  0x3CB923: {'name': 'PrevUUID',
    'type': 'binary',
    'level': 2,
    'documentation': 'definition:- An ID that identifies the previous `Segment` of a `Linked Segment`.\nusage notes:- If the `Segment` is a part of a `Linked Segment` that uses\nHard Linking ((#hard-linking)), then either the\n`PrevUUID` or the `NextUUID` element is\n**REQUIRED**. If a `Segment` contains a `PrevUUID`\nbut not a `NextUUID`, then it **MAY** be considered as the\nlast `Segment` of the `Linked Segment`. The `PrevUUID`\n**MUST NOT** be equal to the `SegmentUUID`.\n'},
  0x3C83AB: {'name': 'PrevFilename',
    'type': 'utf-8',
    'level': 2,
    'documentation': 'definition:- A filename corresponding to the file of the previous `Linked Segment`.\nusage notes:- Provision of the previous filename is for display convenience,\nbut `PrevUUID` **SHOULD** be considered authoritative for identifying the previous `Segment` in a `Linked Segment`.\n'},
  0x3EB923: {'name': 'NextUUID',
    'type': 'binary',
    'level': 2,
    'documentation': 'definition:- An ID that identifies the next `Segment` of a `Linked Segment`.\nusage notes:- If the `Segment` is a part of a `Linked Segment` that uses Hard Linking ((#hard-linking)),\nthen either the `PrevUUID` or the `NextUUID` element is **REQUIRED**. If a `Segment` contains a `NextUUID` but not a `PrevUUID`, then it **MAY** be considered as the first `Segment` of the `Linked Segment`. The `NextUUID` **MUST NOT** be equal to the `SegmentUUID`.\n'},
  0x3E83BB: {'name': 'NextFilename',
    'type': 'utf-8',
    'level': 2,
    'documentation': 'definition:- A filename corresponding to the file of the next `Linked Segment`.\nusage notes:- Provision of the next filename is for display convenience,\nbut `NextUUID` **SHOULD** be considered authoritative for identifying the Next `Segment`.\n'},
  0x4444: {'name': 'SegmentFamily',
    'type': 'binary',
    'level': 2,
    'documentation': 'definition:- A UID that all `Segments` of a `Linked Segment` **MUST** share (128 bits). It is equivalent to a UUID v4 [@!RFC9562] with all bits randomly (or pseudorandomly) chosen. An actual UUID v4 value, where some bits are not random, **MAY** also be used.\nusage notes:- If the `Segment` `Info` contains a `ChapterTranslate` element, this element is **REQUIRED**.\n'},
  0x6924: {'name': 'ChapterTranslate',
    'type': 'master',
    'level': 2,
    'documentation': 'definition:- The mapping between this `Segment` and a\n    segment value in the given Chapter Codec.\nrationale:- Chapter Codecs may need to address different segments, but they may not know of the way to identify such segments when stored in Matroska.\nThis element and its child elements add a way to map the internal segments known to the Chapter Codec to the `SegmentUUID`s in Matroska.\nThis allows remuxing a file with Chapter Codec without changing the content of the codec data, just the `Segment` mapping.\n'},
  0x69A5: {'name': 'ChapterTranslateID',
    'type': 'binary',
    'level': 3,
    'documentation': 'definition:- The binary value used to represent this `Segment` in the chapter codec data.\nThe format depends on the `ChapProcessCodecID` used; see (#chapprocesscodecid-element).\n'},
  0x69BF: {'name': 'ChapterTranslateCodec',
    'type': 'uinteger',
    'level': 3,
    'documentation': 'definition:- Applies to the chapter codec of the given chapter edition(s); see (#chapprocesscodecid-element).\n'},
  0x69FC: {'name': 'ChapterTranslateEditionUID',
    'type': 'uinteger',
    'level': 3,
    'documentation': 'definition:- Specifies a chapter edition UID to which this `ChapterTranslate` applies.\nusage notes:- When no `ChapterTranslateEditionUID` is specified in the `ChapterTranslate`, the `ChapterTranslate` applies to all chapter editions found in the `Segment` using the given `ChapterTranslateCodec`.\n'},
  0x2AD7B1: {'name': 'TimestampScale',
    'type': 'uinteger',
    'level': 2,
    'default': '1000000',
    'documentation': 'definition:- Base unit for Segment Ticks and Track Ticks, in nanoseconds. A `TimestampScale` value of 1000000 means scaled timestamps in the `Segment` are expressed in milliseconds; see (#timestamps) on how to interpret timestamps.\n'},
  0x4489: {'name': 'Duration',
    'type': 'float',
    'level': 2,
    'documentation': 'definition:- Duration of the `Segment`, expressed in `Segment` Ticks, which are based on `TimestampScale`; see (#timestamp-ticks).\n'},
  0x4461: {'name': 'DateUTC',
    'type': 'date',
    'level': 2,
    'documentation': 'definition:- The date and time that the `Segment` was created by the muxing application or library.\n'},
  0x7BA9: {'name': 'Title',
    'type': 'utf-8',
    'level': 2,
    'documentation': 'definition:- General name of the `Segment`.\n'},
  0x4D80: {'name': 'MuxingApp',
    'type': 'utf-8',
    'level': 2,
    'documentation': 'definition:- Muxing application or library (example: "libmatroska-0.4.3").\nusage notes:- Include the full name of the application or library followed by the version number.\n'},
  0x5741: {'name': 'WritingApp',
    'type': 'utf-8',
    'level': 2,
    'documentation': 'definition:- Writing application (example: "mkvmerge-0.3.3").\nusage notes:- Include the full name of the application followed by the version number.\n'},
  0x1F43B675: {'name': 'Cluster',
    'type': 'master',
    'level': 1,
    'documentation': 'definition:- The `Top-Level Element` containing the (monolithic) `Block` structure.\n'},
  0xE7: {'name': 'Timestamp',
    'type': 'uinteger',
    'level': 2,
    'documentation': 'definition:- Absolute timestamp of the cluster, expressed in Segment Ticks, which are based on `TimestampScale`; see (#timestamp-ticks).\nusage notes:- This element **SHOULD** be the first child element of the `Cluster` it belongs to\nor the second if that `Cluster` contains a `CRC-32` element ((#crc-32)).\n'},
  0x5854: {'name': 'SilentTracks',
    'type': 'master',
    'level': 2,
    'documentation': 'definition:- The list of tracks that are not used in that part of the stream.\nIt is useful when using overlay tracks for seeking or deciding what track to use.\n'},
  0x58D7: {'name': 'SilentTrackNumber',
    'type': 'uinteger',
    'level': 3,
    'documentation': 'definition:- One of the track numbers that is not used from now on in the stream.\nIt could change later if not specified as silent in a further `Cluster`.\n'},
  0xA7: {'name': 'Position',
    'type': 'uinteger',
    'level': 2,
    'documentation': 'definition:- The `Segment Position` of the `Cluster` in the `Segment` (0 in live streams).\nIt might help to resynchronize the offset on damaged streams.\n'},
  0xAB: {'name': 'PrevSize',
    'type': 'uinteger',
    'level': 2,
    'documentation': 'definition:- Size of the previous `Cluster`, in octets. Can be useful for backward playing.\n'},
  0xA3: {'name': 'SimpleBlock',
    'type': 'binary',
    'level': 2,
    'documentation': 'definition:- Similar to `Block` (see (#block-structure)) but without all the extra information.\nMostly used to reduce overhead when no extra feature is needed; see (#simpleblock-structure) on `SimpleBlock` Structure.\n'},
  0xA0: {'name': 'BlockGroup',
    'type': 'master',
    'level': 2,
    'documentation': 'definition:- Basic container of information containing a single `Block` and information specific to that `Block`.\n'},
  0xA1: {'name': 'Block',
    'type': 'binary',
    'level': 3,
    'documentation': 'definition:- `Block` containing the actual data to be rendered and a timestamp relative to the `Cluster` Timestamp;\nsee (#block-structure) on `Block` Structure.\n'},
  0xA2: {'name': 'BlockVirtual',
    'type': 'binary',
    'level': 3,
    'documentation': 'definition:- A `Block` with no data. It must be stored in the stream at the place the real `Block` would be in display order.\n\n'},
  0x75A1: {'name': 'BlockAdditions',
    'type': 'master',
    'level': 3,
    'documentation': 'definition:- Contains additional binary data to complete the `Block` element; see [@?I-D.ietf-cellar-codec, section 4.1.5] for more information.\nAn EBML parser that has no knowledge of the `Block` structure could still see and use/skip these data.\n'},
  0xA6: {'name': 'BlockMore',
    'type': 'master',
    'level': 4,
    'documentation': 'definition:- Contains the `BlockAdditional` and some parameters.\n'},
  0xA5: {'name': 'BlockAdditional',
    'type': 'binary',
    'level': 5,
    'documentation': 'definition:- Interpreted by the codec as it wishes (using the `BlockAddID`).\n'},
  0xEE: {'name': 'BlockAddID',
    'type': 'uinteger',
    'level': 5,
    'default': '1',
    'documentation': 'definition:- An ID that identifies how to interpret the `BlockAdditional` data; see [@?I-D.ietf-cellar-codec, section 4.1.5] for\n    more information. A value of 1 indicates that the `BlockAdditional` data is\n    defined by the codec. Any other value indicates that the `BlockAdditional` data\n    should be handled according to the `BlockAddIDType` that is located in the\n`TrackEntry`.\nusage notes:- Each `BlockAddID` value **MUST** be unique between all `BlockMore` elements found in a `BlockAdditions` element. To keep `MaxBlockAdditionID` as low as possible, small values **SHOULD** be used.\n'},
  0x9B: {'name': 'BlockDuration',
    'type': 'uinteger',
    'level': 3,
    'documentation': 'definition:- The duration of the `Block`, expressed in Track Ticks; see (#timestamp-ticks).\nThe `BlockDuration` element can be useful\nat the end of a `Track` to define the duration of the last frame (as\nthere is no subsequent `Block` available) or when there is a break in a\ntrack like for subtitle tracks.\n'},
  0xFA: {'name': 'ReferencePriority',
    'type': 'uinteger',
    'level': 3,
    'default': '0',
    'documentation': 'definition:- This frame is referenced and has the specified cache priority.\nIn the cache, only a frame of the same or higher priority can replace this frame. A value of 0 means the frame is not referenced.\n'},
  0xFB: {'name': 'ReferenceBlock',
    'type': 'integer',
    'level': 3,
    'documentation': 'definition:- A timestamp value, relative to the timestamp of the `Block` in this `BlockGroup`, expressed in Track Ticks; see (#timestamp-ticks).\nThis is used to reference other frames necessary to decode this frame.\nThe relative value **SHOULD** correspond to a valid `Block` that this `Block` depends on.\nHistorically, `Matroska Writers` didn''t write the actual `Block(s)` that this `Block` depends on, but they did write *some* `Block(s)` in the past.\n\nThe value "0" **MAY** also be used to signify that this `Block` cannot be decoded on its own, but the necessary reference `Block(s)` is unknown. In this case, other `ReferenceBlock` elements **MUST NOT** be found in the same `BlockGroup`. If the `BlockGroup` doesn''t have a `ReferenceBlock` element, then the `Block` it contains can be decoded without using any other `Block` data.\n'},
  0xFD: {'name': 'ReferenceVirtual',
    'type': 'integer',
    'level': 3,
    'documentation': 'definition:- The `Segment Position` of the data that would otherwise be in position of the virtual block.\n'},
  0xA4: {'name': 'CodecState',
    'type': 'binary',
    'level': 3,
    'documentation': 'definition:- The new codec state to use. Data interpretation is private to the codec.\nThis information **SHOULD** always be referenced by a seek entry.\n'},
  0x75A2: {'name': 'DiscardPadding',
    'type': 'integer',
    'level': 3,
    'documentation': 'definition:- Duration of the silent data added to the `Block`, expressed in\n    Matroska Ticks -- i.e., in nanoseconds; see (#timestamp-ticks)\n(padding at the end of the `Block` for positive values and at the\nbeginning of the `Block` for negative values).  The duration of\n`DiscardPadding` is not calculated in the duration of the\n`TrackEntry` and **SHOULD** be discarded during\nplayback.\n'},
  0x8E: {'name': 'Slices',
    'type': 'master',
    'level': 3,
    'documentation': 'definition:- Contains slices description.\n'},
  0xE8: {'name': 'TimeSlice',
    'type': 'master',
    'level': 4,
    'documentation': 'definition:- Contains extra time information about the data contained in the `Block`.\nBeing able to interpret this element is not required for playback.\n'},
  0xCC: {'name': 'LaceNumber',
    'type': 'uinteger',
    'level': 5,
    'documentation': 'definition:- The reverse number of the frame in the lace (0 is the last frame, 1 is the next to last, etc.).\nBeing able to interpret this element is not required for playback.\n'},
  0xCD: {'name': 'FrameNumber',
    'type': 'uinteger',
    'level': 5,
    'default': '0',
    'documentation': 'definition:- The number of the frame to generate from this lace with this delay\n(allows for the generation of many frames from the same Block/Frame).\n'},
  0xCB: {'name': 'BlockAdditionID',
    'type': 'uinteger',
    'level': 5,
    'default': '0',
    'documentation': 'definition:- The ID of the `BlockAdditional` element (0 is the main `Block`).\n'},
  0xCE: {'name': 'Delay',
    'type': 'uinteger',
    'level': 5,
    'default': '0',
    'documentation': 'definition:- The delay to apply to the element, expressed in Track Ticks; see (#timestamp-ticks).\n'},
  0xCF: {'name': 'SliceDuration',
    'type': 'uinteger',
    'level': 5,
    'default': '0',
    'documentation': 'definition:- The duration to apply to the element, expressed in Track Ticks; see (#timestamp-ticks).\n'},
  0xC8: {'name': 'ReferenceFrame',
    'type': 'master',
    'level': 3,
    'documentation': 'definition:- Contains information about the last reference frame. See [@?DivXTrickTrack].\n'},
  0xC9: {'name': 'ReferenceOffset',
    'type': 'uinteger',
    'level': 4,
    'documentation': 'definition:- The relative offset, in bytes, from the previous `BlockGroup` element for this Smooth FF/RW video track to the containing `BlockGroup`\nelement. See [@?DivXTrickTrack].\n'},
  0xCA: {'name': 'ReferenceTimestamp',
    'type': 'uinteger',
    'level': 4,
    'documentation': 'definition:- The timestamp of the `BlockGroup` pointed to by ReferenceOffset, expressed in Track Ticks; see (#timestamp-ticks). See [@?DivXTrickTrack].\n'},
  0xAF: {'name': 'EncryptedBlock',
    'type': 'binary',
    'level': 2,
    'documentation': 'definition:- Similar to `SimpleBlock` (see (#simpleblock-structure)),\nbut the data inside the `Block` are Transformed (encrypted and/or signed).\n'},
  0x1654AE6B: {'name': 'Tracks',
    'type': 'master',
    'level': 1,
    'documentation': 'definition:- A `Top-Level Element` of information with many tracks described.\n'},
  0xAE: {'name': 'TrackEntry',
    'type': 'master',
    'level': 2,
    'documentation': 'definition:- Describes a track with all elements.\n'},
  0xD7: {'name': 'TrackNumber',
    'type': 'uinteger',
    'level': 3,
    'documentation': 'definition:- The track number as used in the `Block` Header.\n'},
  0x73C5: {'name': 'TrackUID',
    'type': 'uinteger',
    'level': 3,
    'documentation': 'definition:- A UID that identifies the `Track`.\n'},
  0x83: {'name': 'TrackType',
    'type': 'uinteger',
    'level': 3,
    'enum': {1: 'video', 2: 'audio', 3: 'complex', 16: 'logo', 17: 'subtitle', 18: 'buttons', 32: 'control', 33: 'metadata'},
    'documentation': 'definition:- The `TrackType` defines the type of each frame found in the `Track`.\nThe value **SHOULD** be stored on 1 octet.\n'},
  0xB9: {'name': 'FlagEnabled',
    'type': 'uinteger',
    'level': 3,
    'default': '1',
    'documentation': 'definition:- Set to 1 if the track is usable. It is possible to turn a track that is not usable into a usable track using chapter codecs or control tracks.\n'},
  0x88: {'name': 'FlagDefault',
    'type': 'uinteger',
    'level': 3,
    'default': '1',
    'documentation': 'definition:- Set to 1 if the track (audio, video, or subtitles) is eligible for automatic selection by the player; see (#default-track-selection) for more details.\n'},
  0x55AA: {'name': 'FlagForced',
    'type': 'uinteger',
    'level': 3,
    'default': '0',
    'documentation': 'definition:- Applies only to subtitles. Set to 1 if the track is eligible for automatic selection by the player if it matches the user''s language preference,\neven if the user''s preferences would not normally enable subtitles with the selected audio track;\nthis can be used for tracks containing only translations of audio in foreign languages or on-screen text.\nSee (#default-track-selection) for more details.\n'},
  0x55AB: {'name': 'FlagHearingImpaired',
    'type': 'uinteger',
    'level': 3,
    'documentation': 'definition:- Set to 1 if and only if the track is suitable for users with hearing impairments.\n'},
  0x55AC: {'name': 'FlagVisualImpaired',
    'type': 'uinteger',
    'level': 3,
    'documentation': 'definition:- Set to 1 if and only if the track is suitable for users with visual impairments.\n'},
  0x55AD: {'name': 'FlagTextDescriptions',
    'type': 'uinteger',
    'level': 3,
    'documentation': 'definition:- Set to 1 if and only if the track contains textual descriptions of video content.\n'},
  0x55AE: {'name': 'FlagOriginal',
    'type': 'uinteger',
    'level': 3,
    'documentation': 'definition:- Set to 1 if and only if the track is in the content''s original language.\n'},
  0x55AF: {'name': 'FlagCommentary',
    'type': 'uinteger',
    'level': 3,
    'documentation': 'definition:- Set to 1 if and only if the track contains commentary.\n'},
  0x9C: {'name': 'FlagLacing',
    'type': 'uinteger',
    'level': 3,
    'default': '1',
    'documentation': 'definition:- Set to 1 if the track **MAY** contain blocks that use lacing.\n    When set to 0, all blocks **MUST** have their lacing flags set to "no lacing"; see (#block-lacing) on ''Block'' Lacing.\n'},
  0x6DE7: {'name': 'MinCache',
    'type': 'uinteger',
    'level': 3,
    'default': '0',
    'documentation': 'definition:- The minimum number of frames a player should be able to cache during playback.\nIf set to 0, the reference pseudo-cache system is not used.\n'},
  0x6DF8: {'name': 'MaxCache',
    'type': 'uinteger',
    'level': 3,
    'documentation': 'definition:- The maximum cache size necessary to store referenced frames in and the current frame.\n0 means no cache is needed.\n'},
  0x23E383: {'name': 'DefaultDuration',
    'type': 'uinteger',
    'level': 3,
    'documentation': 'definition:- Number of nanoseconds per frame, expressed in Matroska Ticks -- i.e., in nanoseconds; see (#timestamp-ticks)\n("frame" in the Matroska sense -- one element put into a (Simple)Block).\n'},
  0x234E7A: {'name': 'DefaultDecodedFieldDuration',
    'type': 'uinteger',
    'level': 3,
    'documentation': 'definition:- The period between two successive fields at the output of the decoding process, expressed in Matroska Ticks -- i.e., in nanoseconds; see (#timestamp-ticks).\nSee (#defaultdecodedfieldduration) for more information.\n'},
  0x23314F: {'name': 'TrackTimestampScale',
    'type': 'float',
    'level': 3,
    'default': '0x1p+0',
    'documentation': 'definition:- The scale to apply on this track to work at normal speed in relation with other tracks\n(mostly used to adjust video speed when the audio length differs).\n'},
  0x537F: {'name': 'TrackOffset',
    'type': 'integer',
    'level': 3,
    'default': '0',
    'documentation': 'definition:- A value to add to the `Block`''s Timestamp, expressed in Matroska Ticks -- i.e., in nanoseconds; see (#timestamp-ticks).\nThis can be used to adjust the playback offset of a track.\n'},
  0x55EE: {'name': 'MaxBlockAdditionID',
    'type': 'uinteger',
    'level': 3,
    'default': '0',
    'documentation': 'definition:- The maximum value of `BlockAddID` ((#blockaddid-element)).\nA value of 0 means there is no `BlockAdditions` ((#blockadditions-element)) for this track.\n'},
  0x41E4: {'name': 'BlockAdditionMapping',
    'type': 'master',
    'level': 3,
    'documentation': 'definition:- Contains elements that extend the track format by adding content either to each frame,\nwith `BlockAddID` ((#blockaddid-element)), or to the track as a whole\nwith `BlockAddIDExtraData`.\n'},
  0x41F0: {'name': 'BlockAddIDValue',
    'type': 'uinteger',
    'level': 4,
    'documentation': 'definition:- If the track format extension needs content beside frames,\nthe value refers to the `BlockAddID` ((#blockaddid-element)) value being described.\nusage notes:- To keep `MaxBlockAdditionID` as low as possible, small values **SHOULD** be used.\n'},
  0x41A4: {'name': 'BlockAddIDName',
    'type': 'string',
    'level': 4,
    'documentation': 'definition:- A human-friendly name describing the type of `BlockAdditional` data,\nas defined by the associated `Block Additional Mapping`.\n'},
  0x41E7: {'name': 'BlockAddIDType',
    'type': 'uinteger',
    'level': 4,
    'default': '0',
    'documentation': 'definition:- Stores the registered identifier of the `Block Additional Mapping`\nto define how the `BlockAdditional` data should be handled.\nusage notes:- If `BlockAddIDType` is 0, the `BlockAddIDValue` and corresponding `BlockAddID` values **MUST** be 1.\n'},
  0x41ED: {'name': 'BlockAddIDExtraData',
    'type': 'binary',
    'level': 4,
    'documentation': 'definition:- Extra binary data that the `BlockAddIDType` can use to interpret the `BlockAdditional` data.\nThe interpretation of the binary data depends on the `BlockAddIDType` value and the corresponding `Block Additional Mapping`.\n'},
  0x536E: {'name': 'Name',
    'type': 'utf-8',
    'level': 3,
    'documentation': 'definition:- A human-readable track name.\n'},
  0x22B59C: {'name': 'Language',
    'type': 'string',
    'level': 3,
    'default': 'eng',
    'documentation': 'definition:- The language of the track,\nin the Matroska languages form; see (#language-codes) on language codes.\nThis element **MUST** be ignored if the `LanguageBCP47` element is used in the same `TrackEntry`.\n'},
  0x22B59D: {'name': 'LanguageBCP47',
    'type': 'string',
    'level': 3,
    'documentation': 'definition:- The language of the track,\nin the form defined in [@!RFC5646]; see (#language-codes) on language codes.\nIf this element is used, then any `Language` elements used in the same `TrackEntry` **MUST** be ignored.\n'},
  0x86: {'name': 'CodecID',
    'type': 'string',
    'level': 3,
    'documentation': 'definition:- An ID corresponding to the codec;\nsee [@?I-D.ietf-cellar-codec] for more info.\n'},
  0x63A2: {'name': 'CodecPrivate',
    'type': 'binary',
    'level': 3,
    'documentation': 'definition:- Private data only known to the codec.\n'},
  0x258688: {'name': 'CodecName',
    'type': 'utf-8',
    'level': 3,
    'documentation': 'definition:- A human-readable string specifying the codec.\n'},
  0x7446: {'name': 'AttachmentLink',
    'type': 'uinteger',
    'level': 3,
    'documentation': 'definition:- The UID of an attachment that is used by this codec.\nusage notes:- The value **MUST** match the `FileUID` value of an attachment found in this `Segment`.\n'},
  0x3A9697: {'name': 'CodecSettings',
    'type': 'utf-8',
    'level': 3,
    'documentation': 'definition:- A string describing the encoding setting used.\n'},
  0x3B4040: {'name': 'CodecInfoURL',
    'type': 'string',
    'level': 3,
    'documentation': 'definition:- A URL to find information about the codec used.\n'},
  0x26B240: {'name': 'CodecDownloadURL',
    'type': 'string',
    'level': 3,
    'documentation': 'definition:- A URL to download information about the codec used.\n'},
  0xAA: {'name': 'CodecDecodeAll',
    'type': 'uinteger',
    'level': 3,
    'default': '1',
    'documentation': 'definition:- Set to 1 if the codec can decode potentially damaged data.\n'},
  0x6FAB: {'name': 'TrackOverlay',
    'type': 'uinteger',
    'level': 3,
    'documentation': 'definition:- Specify that this track is an overlay track for the `Track` specified (in the u-integer).\nThis means that when this track has a gap on `SilentTracks`, the overlay track should be used instead. The order of multiple `TrackOverlay` matters; the first one is the one that should be used.\nIf the first one is not found, it should be the second, etc.\n'},
  0x56AA: {'name': 'CodecDelay',
    'type': 'uinteger',
    'level': 3,
    'default': '0',
    'documentation': 'definition:- The built-in delay for the codec, expressed in Matroska Ticks -- i.e., in nanoseconds; see (#timestamp-ticks).\nIt represents the number of codec samples that will be discarded by the decoder during playback.\nThis timestamp value **MUST** be subtracted from each frame timestamp in order to get the timestamp that will be actually played.\nThe value **SHOULD** be small so the muxing of tracks with the same actual timestamp are in the same `Cluster`.\n'},
  0x56BB: {'name': 'SeekPreRoll',
    'type': 'uinteger',
    'level': 3,
    'default': '0',
    'documentation': 'definition:- After a discontinuity, the duration of the data\nthat the decoder **MUST** decode before the decoded data is valid, expressed in Matroska Ticks -- i.e., in nanoseconds; see (#timestamp-ticks).\n'},
  0x6624: {'name': 'TrackTranslate',
    'type': 'master',
    'level': 3,
    'documentation': 'definition:- The mapping between this `TrackEntry` and a track value in the given Chapter Codec.\nrationale:- Chapter Codecs may need to address content in a specific track, but they may not know of the way to identify tracks in Matroska.\nThis element and its child elements add a way to map the internal tracks known to the Chapter Codec to the track IDs in Matroska.\nThis allows remuxing a file with Chapter Codec without changing the content of the codec data, just the track mapping.\n'},
  0x66A5: {'name': 'TrackTranslateTrackID',
    'type': 'binary',
    'level': 4,
    'documentation': 'definition:- The binary value used to represent this `TrackEntry` in the chapter codec data.\nThe format depends on the `ChapProcessCodecID` used; see (#chapprocesscodecid-element).\n'},
  0x66BF: {'name': 'TrackTranslateCodec',
    'type': 'uinteger',
    'level': 4,
    'documentation': 'definition:- Applies to the chapter codec of the given chapter edition(s); see (#chapprocesscodecid-element).\n'},
  0x66FC: {'name': 'TrackTranslateEditionUID',
    'type': 'uinteger',
    'level': 4,
    'documentation': 'definition:- Specifies a chapter edition UID to which this `TrackTranslate` applies.\nusage notes:- When no `TrackTranslateEditionUID` is specified in the `TrackTranslate`, the `TrackTranslate` applies to all chapter editions found in the `Segment` using the given `TrackTranslateCodec`.\n'},
  0xE0: {'name': 'Video',
    'type': 'master',
    'level': 3,
    'documentation': 'definition:- Video settings.\n'},
  0x9A: {'name': 'FlagInterlaced',
    'type': 'uinteger',
    'level': 4,
    'default': '0',
    'enum': {0: 'undetermined', 1: 'interlaced', 2: 'progressive'},
    'documentation': 'definition:- Specifies whether the video frames in this track are interlaced.\n'},
  0x9D: {'name': 'FieldOrder',
    'type': 'uinteger',
    'level': 4,
    'default': '2',
    'enum': {0: 'progressive', 1: 'tff', 2: 'undetermined', 6: 'bff', 9: 'tff (interleaved)', 14: 'bff (interleaved)'},
    'documentation': 'definition:- Specifies the field ordering of video frames in this track.\nusage notes:- If `FlagInterlaced` is not set to 1, this element **MUST** be ignored.\n'},
  0x53B8: {'name': 'StereoMode',
    'type': 'uinteger',
    'level': 4,
    'default': '0',
    'enum': {0: 'mono', 1: 'side by side (left eye first)', 2: 'top - bottom (right eye is first)', 3: 'top - bottom (left eye is first)', 4: 'checkboard (right eye is first)', 5: 'checkboard (left eye is first)', 6: 'row interleaved (right eye is first)', 7: 'row interleaved (left eye is first)', 8: 'column interleaved (right eye is first)', 9: 'column interleaved (left eye is first)', 10: 'anaglyph (cyan/red)', 11: 'side by side (right eye first)', 12: 'anaglyph (green/magenta)', 13: 'both eyes laced in one Block (left eye is first)', 14: 'both eyes laced in one Block (right eye is first)'},
    'documentation': 'definition:- Stereo-3D video mode. See (#multi-planar-and-3d-videos) for more details.\n'},
  0x53C0: {'name': 'AlphaMode',
    'type': 'uinteger',
    'level': 4,
    'default': '0',
    'enum': {0: 'none', 1: 'present'},
    'documentation': 'definition:- Indicates whether the `BlockAdditional` element with `BlockAddID` of "1"\n    contains Alpha data as defined by the Codec Mapping for the `CodecID`.\n Undefined values (i.e., values other than 0 or 1) **SHOULD NOT** be used, as the\n behavior of known implementations is different.\n'},
  0x53B9: {'name': 'OldStereoMode',
    'type': 'uinteger',
    'level': 4,
    'enum': {0: 'mono', 1: 'right eye', 2: 'left eye', 3: 'both eyes'},
    'documentation': 'definition:- Bogus `StereoMode` value used in old versions of [@?libmatroska].\nusage notes:- This element **MUST NOT** be used. It was an incorrect value used in libmatroska up to 0.9.0.\n'},
  0xB0: {'name': 'PixelWidth',
    'type': 'uinteger',
    'level': 4,
    'documentation': 'definition:- Width of the encoded video frames in pixels.\n'},
  0xBA: {'name': 'PixelHeight',
    'type': 'uinteger',
    'level': 4,
    'documentation': 'definition:- Height of the encoded video frames in pixels.\n'},
  0x54AA: {'name': 'PixelCropBottom',
    'type': 'uinteger',
    'level': 4,
    'default': '0',
    'documentation': 'definition:- The number of video pixels to remove at the bottom of the image.\n'},
  0x54BB: {'name': 'PixelCropTop',
    'type': 'uinteger',
    'level': 4,
    'default': '0',
    'documentation': 'definition:- The number of video pixels to remove at the top of the image.\n'},
  0x54CC: {'name': 'PixelCropLeft',
    'type': 'uinteger',
    'level': 4,
    'default': '0',
    'documentation': 'definition:- The number of video pixels to remove on the left of the image.\n'},
  0x54DD: {'name': 'PixelCropRight',
    'type': 'uinteger',
    'level': 4,
    'default': '0',
    'documentation': 'definition:- The number of video pixels to remove on the right of the image.\n'},
  0x54B0: {'name': 'DisplayWidth',
    'type': 'uinteger',
    'level': 4,
    'documentation': 'definition:- Width of the video frames to display. Applies to the video frame after cropping (PixelCrop* Elements).\n'},
  0x54BA: {'name': 'DisplayHeight',
    'type': 'uinteger',
    'level': 4,
    'documentation': 'definition:- Height of the video frames to display. Applies to the video frame after cropping (PixelCrop* Elements).\n'},
  0x54B2: {'name': 'DisplayUnit',
    'type': 'uinteger',
    'level': 4,
    'default': '0',
    'enum': {0: 'pixels', 1: 'centimeters', 2: 'inches', 3: 'display aspect ratio', 4: 'unknown'},
    'documentation': 'definition:- How `DisplayWidth` and `DisplayHeight` are interpreted.\n'},
  0x54B3: {'name': 'AspectRatioType',
    'type': 'uinteger',
    'level': 4,
    'default': '0',
    'enum': {0: 'free resizing', 1: 'keep aspect ratio', 2: 'fixed'},
    'documentation': 'definition:- Specifies the possible modifications to the aspect ratio.\n'},
  0x2EB524: {'name': 'UncompressedFourCC',
    'type': 'binary',
    'level': 4,
    'documentation': 'definition:- Specifies the uncompressed pixel format used for the `Track`''s data as a FourCC.\nThis value is similar in scope to the biCompression value of AVI''s `BITMAPINFO` [@?AVIFormat]. There is neither a definitive list of FourCC values nor an official registry. Some common values for YUV pixel formats can be found at [@?MSYUV8], [@?MSYUV16], and [@?FourCC-YUV]. Some common values for uncompressed RGB pixel formats can be found at [@?MSRGB] and [@?FourCC-RGB].\n'},
  0x2FB523: {'name': 'GammaValue',
    'type': 'float',
    'level': 4,
    'documentation': 'definition:- Gamma value.\n'},
  0x2383E3: {'name': 'FrameRate',
    'type': 'float',
    'level': 4,
    'documentation': 'definition:- Number of frames per second. This value is informational only. It is intended for constant frame rate streams and should not be\n    used for a variable frame rate `TrackEntry`.\n'},
  0x55B0: {'name': 'Colour',
    'type': 'master',
    'level': 4,
    'documentation': 'definition:- Settings describing the color format.\n'},
  0x55B1: {'name': 'MatrixCoefficients',
    'type': 'uinteger',
    'level': 5,
    'default': '2',
    'enum': {0: 'Identity', 1: 'ITU-R BT.709', 2: 'unspecified', 3: 'reserved', 4: 'US FCC 73.682', 5: 'ITU-R BT.470BG', 6: 'SMPTE 170M', 7: 'SMPTE 240M', 8: 'YCoCg', 9: 'BT2020 Non-constant Luminance', 10: 'BT2020 Constant Luminance', 11: 'SMPTE ST 2085', 12: 'Chroma-derived Non-constant Luminance', 13: 'Chroma-derived Constant Luminance', 14: 'ITU-R BT.2100-0'},
    'documentation': 'definition:- The Matrix Coefficients of the video used to derive luma and chroma values from red, green, and blue color primaries.\nFor clarity, the value and meanings for `MatrixCoefficients` are adopted from Table 4 of [@!ITU-H.273].\n'},
  0x55B2: {'name': 'BitsPerChannel',
    'type': 'uinteger',
    'level': 5,
    'default': '0',
    'documentation': 'definition:- Number of decoded bits per channel. A value of 0 indicates that the `BitsPerChannel` is unspecified.\n'},
  0x55B3: {'name': 'ChromaSubsamplingHorz',
    'type': 'uinteger',
    'level': 5,
    'documentation': 'definition:- The number of pixels to remove in the Cr and Cb channels for every pixel not removed horizontally. Example: For video with 4:2:0 chroma subsampling, the `ChromaSubsamplingHorz`\n    **SHOULD** be set to 1.\n'},
  0x55B4: {'name': 'ChromaSubsamplingVert',
    'type': 'uinteger',
    'level': 5,
    'documentation': 'definition:- The number of pixels to remove in the Cr and Cb channels for every pixel not removed vertically.\nExample: For video with 4:2:0 chroma subsampling, the `ChromaSubsamplingVert`\n**SHOULD** be set to 1.\n'},
  0x55B5: {'name': 'CbSubsamplingHorz',
    'type': 'uinteger',
    'level': 5,
    'documentation': 'definition:- The number of pixels to remove in the Cb channel for every pixel not removed horizontally.\nThis is additive with `ChromaSubsamplingHorz`.\nExample: For video with 4:2:1 chroma\nsubsampling, the `ChromaSubsamplingHorz` **SHOULD** be set to 1, and `CbSubsamplingHorz` **SHOULD** be set to 1.\n'},
  0x55B6: {'name': 'CbSubsamplingVert',
    'type': 'uinteger',
    'level': 5,
    'documentation': 'definition:- The number of pixels to remove in the Cb channel for every pixel not removed vertically.\nThis is additive with `ChromaSubsamplingVert`.\n'},
  0x55B7: {'name': 'ChromaSitingHorz',
    'type': 'uinteger',
    'level': 5,
    'default': '0',
    'enum': {0: 'unspecified', 1: 'left collocated', 2: 'half'},
    'documentation': 'definition:- How chroma is subsampled horizontally.\n'},
  0x55B8: {'name': 'ChromaSitingVert',
    'type': 'uinteger',
    'level': 5,
    'default': '0',
    'enum': {0: 'unspecified', 1: 'top collocated', 2: 'half'},
    'documentation': 'definition:- How chroma is subsampled vertically.\n'},
  0x55B9: {'name': 'Range',
    'type': 'uinteger',
    'level': 5,
    'default': '0',
    'enum': {0: 'unspecified', 1: 'broadcast range', 2: 'full range (no clipping)', 3: 'defined by MatrixCoefficients / TransferCharacteristics'},
    'documentation': 'definition:- Clipping of the color ranges.\n'},
  0x55BA: {'name': 'TransferCharacteristics',
    'type': 'uinteger',
    'level': 5,
    'default': '2',
    'enum': {0: 'reserved', 1: 'ITU-R BT.709', 2: 'unspecified', 3: 'reserved2', 4: 'Gamma 2.2 curve - BT.470M', 5: 'Gamma 2.8 curve - BT.470BG', 6: 'SMPTE 170M', 7: 'SMPTE 240M', 8: 'Linear', 9: 'Log', 10: 'Log Sqrt', 11: 'IEC 61966-2-4', 12: 'ITU-R BT.1361 Extended Colour Gamut', 13: 'IEC 61966-2-1', 14: 'ITU-R BT.2020 10 bit', 15: 'ITU-R BT.2020 12 bit', 16: 'ITU-R BT.2100 Perceptual Quantization', 17: 'SMPTE ST 428-1', 18: 'ARIB STD-B67 (HLG)'},
    'documentation': 'definition:- The transfer characteristics of the video. For clarity,\nthe value and meanings for `TransferCharacteristics` are adopted from Table 3 of [@!ITU-H.273].\n'},
  0x55BB: {'name': 'Primaries',
    'type': 'uinteger',
    'level': 5,
    'default': '2',
    'enum': {0: 'reserved', 1: 'ITU-R BT.709', 2: 'unspecified', 3: 'reserved2', 4: 'ITU-R BT.470M', 5: 'ITU-R BT.470BG - BT.601 625', 6: 'ITU-R BT.601 525 - SMPTE 170M', 7: 'SMPTE 240M', 8: 'FILM', 9: 'ITU-R BT.2020', 10: 'SMPTE ST 428-1', 11: 'SMPTE RP 432-2', 12: 'SMPTE EG 432-2', 22: 'EBU Tech. 3213-E - JEDEC P22 phosphors'},
    'documentation': 'definition:- The color primaries of the video. For clarity,\nthe value and meanings for `Primaries` are adopted from Table 2 of [@!ITU-H.273].\n'},
  0x55BC: {'name': 'MaxCLL',
    'type': 'uinteger',
    'level': 5,
    'documentation': 'definition:- Maximum brightness of a single pixel (Maximum Content Light Level)\nin candelas per square meter (cd/m^2^).\n'},
  0x55BD: {'name': 'MaxFALL',
    'type': 'uinteger',
    'level': 5,
    'documentation': 'definition:- Maximum brightness of a single full frame (Maximum Frame-Average Light Level)\nin candelas per square meter (cd/m^2^).\n'},
  0x55D0: {'name': 'MasteringMetadata',
    'type': 'master',
    'level': 5,
    'documentation': 'definition:- SMPTE 2086 mastering data.\n'},
  0x55D1: {'name': 'PrimaryRChromaticityX',
    'type': 'float',
    'level': 6,
    'documentation': 'definition:- Red X chromaticity coordinate, as defined by [@!CIE-1931].\n'},
  0x55D2: {'name': 'PrimaryRChromaticityY',
    'type': 'float',
    'level': 6,
    'documentation': 'definition:- Red Y chromaticity coordinate, as defined by [@!CIE-1931].\n'},
  0x55D3: {'name': 'PrimaryGChromaticityX',
    'type': 'float',
    'level': 6,
    'documentation': 'definition:- Green X chromaticity coordinate, as defined by [@!CIE-1931].\n'},
  0x55D4: {'name': 'PrimaryGChromaticityY',
    'type': 'float',
    'level': 6,
    'documentation': 'definition:- Green Y chromaticity coordinate, as defined by [@!CIE-1931].\n'},
  0x55D5: {'name': 'PrimaryBChromaticityX',
    'type': 'float',
    'level': 6,
    'documentation': 'definition:- Blue X chromaticity coordinate, as defined by [@!CIE-1931].\n'},
  0x55D6: {'name': 'PrimaryBChromaticityY',
    'type': 'float',
    'level': 6,
    'documentation': 'definition:- Blue Y chromaticity coordinate, as defined by [@!CIE-1931].\n'},
  0x55D7: {'name': 'WhitePointChromaticityX',
    'type': 'float',
    'level': 6,
    'documentation': 'definition:- White X chromaticity coordinate, as defined by [@!CIE-1931].\n'},
  0x55D8: {'name': 'WhitePointChromaticityY',
    'type': 'float',
    'level': 6,
    'documentation': 'definition:- White Y chromaticity coordinate, as defined by [@!CIE-1931].\n'},
  0x55D9: {'name': 'LuminanceMax',
    'type': 'float',
    'level': 6,
    'documentation': 'definition:- Maximum luminance. Represented in candelas per square meter (cd/m^2^).\n'},
  0x55DA: {'name': 'LuminanceMin',
    'type': 'float',
    'level': 6,
    'documentation': 'definition:- Minimum luminance. Represented in candelas per square meter (cd/m^2^).\n'},
  0x7670: {'name': 'Projection',
    'type': 'master',
    'level': 4,
    'documentation': 'definition:- Describes the video projection details. Used to render spherical or VR videos or to flip videos horizontally or vertically.\n'},
  0x7671: {'name': 'ProjectionType',
    'type': 'uinteger',
    'level': 5,
    'default': '0',
    'enum': {0: 'rectangular', 1: 'equirectangular', 2: 'cubemap', 3: 'mesh'},
    'documentation': 'definition:- Describes the projection used for this video track.\n'},
  0x7672: {'name': 'ProjectionPrivate',
    'type': 'binary',
    'level': 5,
    'documentation': 'definition:- Private data that only applies to a specific projection.\n*  If `ProjectionType` equals 0 (rectangular),\n     then this element **MUST NOT** be present.\n*  If `ProjectionType` equals 1 (equirectangular), then this element **MUST** be present and contain the same binary data that would be stored inside\n      an ISOBMFF Equirectangular Projection Box ("equi").\n*  If `ProjectionType` equals 2 (cubemap), then this element **MUST** be present and contain the same binary data that would be stored\n      inside an ISOBMFF Cubemap Projection Box ("cbmp").\n*  If `ProjectionType` equals 3 (mesh), then this element **MUST** be present and contain the same binary data that would be stored inside\n       an ISOBMFF Mesh Projection Box ("mshp").\nusage notes:- ISOBMFF box size and FourCC fields are not included in the binary data,\nbut the FullBox version and flag fields are. This is to avoid\nredundant framing information while preserving versioning and semantics between the two container formats.\n'},
  0x7673: {'name': 'ProjectionPoseYaw',
    'type': 'float',
    'level': 5,
    'default': '0x0p+0',
    'documentation': 'definition:- Specifies a yaw rotation to the projection. Value represents a clockwise rotation, in degrees, around the up vector. This rotation must be applied\nbefore any `ProjectionPosePitch` or `ProjectionPoseRoll` rotations.\nThe value of this element **MUST** be in the -180 to 180 degree range, both inclusive.\n\nSetting `ProjectionPoseYaw` to 180 or -180 degrees with `ProjectionPoseRoll` and `ProjectionPosePitch` set to 0 degrees flips the image horizontally.\n'},
  0x7674: {'name': 'ProjectionPosePitch',
    'type': 'float',
    'level': 5,
    'default': '0x0p+0',
    'documentation': 'definition:- Specifies a pitch rotation to the projection. Value represents a counter-clockwise rotation, in degrees, around the right vector. This rotation must be applied\nafter the `ProjectionPoseYaw` rotation and before the `ProjectionPoseRoll` rotation.\nThe value of this element **MUST** be in the -90 to 90 degree range, both inclusive.\n'},
  0x7675: {'name': 'ProjectionPoseRoll',
    'type': 'float',
    'level': 5,
    'default': '0x0p+0',
    'documentation': 'definition:- Specifies a roll rotation to the projection. Value represents a\n    counter-clockwise rotation, in degrees, around the forward vector. This\n    rotation must be applied after the `ProjectionPoseYaw` and\n    `ProjectionPosePitch` rotations.  The value of this element\n    **MUST** be in the -180 to 180 degree range, both inclusive. Setting `ProjectionPoseRoll` to 180 or -180 degrees and\n    `ProjectionPoseYaw` to 180 or -180 degrees with\n    `ProjectionPosePitch` set to 0 degrees flips the image vertically.\n    Setting `ProjectionPoseRoll` to 180 or -180 degrees with\n    `ProjectionPoseYaw` and `ProjectionPosePitch` set to 0 degrees\n    flips the image horizontally and vertically.\n'},
  0xE1: {'name': 'Audio',
    'type': 'master',
    'level': 3,
    'documentation': 'definition:- Audio settings.\n'},
  0xB5: {'name': 'SamplingFrequency',
    'type': 'float',
    'level': 4,
    'default': '0x1.f4p+12',
    'documentation': 'definition:- Sampling frequency in Hz.\n'},
  0x78B5: {'name': 'OutputSamplingFrequency',
    'type': 'float',
    'level': 4,
    'documentation': 'definition:- Real output sampling frequency in Hz that is used for Spectral Band Replication (SBR) techniques.\n'},
  0x9F: {'name': 'Channels',
    'type': 'uinteger',
    'level': 4,
    'default': '1',
    'documentation': 'definition:- Numbers of channels in the track.\n'},
  0x7D7B: {'name': 'ChannelPositions',
    'type': 'binary',
    'level': 4,
    'documentation': 'definition:- Table of horizontal angles for each successive channel.\n'},
  0x6264: {'name': 'BitDepth',
    'type': 'uinteger',
    'level': 4,
    'documentation': 'definition:- Bits per sample, mostly used for PCM.\n'},
  0x52F1: {'name': 'Emphasis',
    'type': 'uinteger',
    'level': 4,
    'default': '0',
    'enum': {0: 'No emphasis', 1: 'CD audio', 2: 'reserved', 3: 'CCIT J.17', 4: 'FM 50', 5: 'FM 75', 10: 'Phono RIAA', 11: 'Phono IEC N78', 12: 'Phono TELDEC', 13: 'Phono EMI', 14: 'Phono Columbia LP', 15: 'Phono LONDON', 16: 'Phono NARTB'},
    'documentation': 'definition:- Audio emphasis applied on audio samples. The player **MUST** apply the inverse emphasis to get the proper audio samples.\n'},
  0xE2: {'name': 'TrackOperation',
    'type': 'master',
    'level': 3,
    'documentation': 'definition:- Operation that needs to be applied on tracks to create this virtual track. For more details, see (#track-operation).\n'},
  0xE3: {'name': 'TrackCombinePlanes',
    'type': 'master',
    'level': 4,
    'documentation': 'definition:- Contains the list of all video plane tracks that need to be combined to create this 3D track.\n'},
  0xE4: {'name': 'TrackPlane',
    'type': 'master',
    'level': 5,
    'documentation': 'definition:- Contains a video plane track that needs to be combined to create this 3D track.\n'},
  0xE5: {'name': 'TrackPlaneUID',
    'type': 'uinteger',
    'level': 6,
    'documentation': 'definition:- The `TrackUID` number of the track representing the plane.\n'},
  0xE6: {'name': 'TrackPlaneType',
    'type': 'uinteger',
    'level': 6,
    'enum': {0: 'left eye', 1: 'right eye', 2: 'background'},
    'documentation': 'definition:- The kind of plane this track corresponds to.\n'},
  0xE9: {'name': 'TrackJoinBlocks',
    'type': 'master',
    'level': 4,
    'documentation': 'definition:- Contains the list of all tracks whose `Blocks` need to be combined to create this virtual track.\n'},
  0xED: {'name': 'TrackJoinUID',
    'type': 'uinteger',
    'level': 5,
    'documentation': 'definition:- The `TrackUID` number of a track whose blocks are used to create this virtual track.\n'},
  0xC0: {'name': 'TrickTrackUID',
    'type': 'uinteger',
    'level': 3,
    'documentation': 'definition:- The `TrackUID` of the Smooth FF/RW video in the paired EBML structure corresponding to this video track. See [@?DivXTrickTrack].\n'},
  0xC1: {'name': 'TrickTrackSegmentUID',
    'type': 'binary',
    'level': 3,
    'documentation': 'definition:- The `SegmentUUID` of the `Segment` containing the track identified by TrickTrackUID. See [@?DivXTrickTrack].\n'},
  0xC6: {'name': 'TrickTrackFlag',
    'type': 'uinteger',
    'level': 3,
    'default': '0',
    'documentation': 'definition:- Set to 1 if this video track is a Smooth FF/RW track. If set to 1, `MasterTrackUID` and `MasterTrackSegUID` should be present, and\n    `BlockGroups` for this track must contain ReferenceFrame structures.\nOtherwise, TrickTrackUID and TrickTrackSegUID must be present if this track has a corresponding Smooth FF/RW track. See [@?DivXTrickTrack].\n'},
  0xC7: {'name': 'TrickMasterTrackUID',
    'type': 'uinteger',
    'level': 3,
    'documentation': 'definition:- The `TrackUID` of the video track in the paired EBML structure that corresponds to this Smooth FF/RW track. See [@?DivXTrickTrack].\n'},
  0xC4: {'name': 'TrickMasterTrackSegmentUID',
    'type': 'binary',
    'level': 3,
    'documentation': 'definition:- The `SegmentUUID` of the `Segment` containing the track identified by MasterTrackUID. See [@?DivXTrickTrack].\n'},
  0x6D80: {'name': 'ContentEncodings',
    'type': 'master',
    'level': 3,
    'documentation': 'definition:- Settings for several content encoding mechanisms like compression or encryption.\n'},
  0x6240: {'name': 'ContentEncoding',
    'type': 'master',
    'level': 4,
    'documentation': 'definition:- Settings for one content encoding like compression or encryption.\n'},
  0x5031: {'name': 'ContentEncodingOrder',
    'type': 'uinteger',
    'level': 5,
    'default': '0',
    'documentation': 'definition:- Defines the order to apply each `ContentEncoding` of the `ContentEncodings`.\nThe decoder/demuxer **MUST** start with the `ContentEncoding` with the highest `ContentEncodingOrder` and work its way down to the `ContentEncoding` with the lowest `ContentEncodingOrder`.\nThis value **MUST** be unique for each `ContentEncoding` found in the `ContentEncodings` of this `TrackEntry`.\n'},
  0x5032: {'name': 'ContentEncodingScope',
    'type': 'uinteger',
    'level': 5,
    'default': '1',
    'enum': {0x1: 'Block', 0x2: 'Private', 0x4: 'Next'},
    'documentation': 'definition:- A bit field that describes which elements have been modified in this way. Values (big-endian) can be OR''ed.\n'},
  0x5033: {'name': 'ContentEncodingType',
    'type': 'uinteger',
    'level': 5,
    'default': '0',
    'enum': {0: 'Compression', 1: 'Encryption'},
    'documentation': 'definition:- A value describing the kind of transformation that is applied.\n'},
  0x5034: {'name': 'ContentCompression',
    'type': 'master',
    'level': 5,
    'documentation': 'definition:- Settings describing the compression used.\nThis element **MUST** be present if the value of `ContentEncodingType` is 0 and absent otherwise.\nEach block **MUST** be decompressable, even if no previous block is available in order to not prevent seeking.\n'},
  0x4254: {'name': 'ContentCompAlgo',
    'type': 'uinteger',
    'level': 6,
    'default': '0',
    'enum': {0: 'zlib', 1: 'bzlib', 2: 'lzo1x', 3: 'Header Stripping'},
    'documentation': 'definition:- The compression algorithm used.\nusage notes:- Compression method "1" (bzlib) and "2" (lzo1x) lack proper documentation on the format, which limits implementation possibilities. Due to licensing conflicts on commonly available libraries'' compression methods, "2" (lzo1x) does not offer widespread interoperability. A `Matroska Writer` **SHOULD NOT** use these compression methods by default. A `Matroska Reader` **MAY** support methods "1" and "2" and **SHOULD** support other methods.\n'},
  0x4255: {'name': 'ContentCompSettings',
    'type': 'binary',
    'level': 6,
    'documentation': 'definition:- Settings that might be needed by the decompressor. For Header Stripping (`ContentCompAlgo`=3),\nthe bytes that were removed from the beginning of each frame of the track.\n'},
  0x5035: {'name': 'ContentEncryption',
    'type': 'master',
    'level': 5,
    'documentation': 'definition:- Settings describing the encryption used.\nThis element **MUST** be present if the value of `ContentEncodingType` is 1 (encryption) and **MUST** be ignored otherwise.\nA `Matroska Player` **MAY** support encryption.\n'},
  0x47E1: {'name': 'ContentEncAlgo',
    'type': 'uinteger',
    'level': 6,
    'default': '0',
    'enum': {0: 'Not encrypted', 1: 'DES', 2: '3DES', 3: 'Twofish', 4: 'Blowfish', 5: 'AES'},
    'documentation': 'definition:- The encryption algorithm used.\n'},
  0x47E2: {'name': 'ContentEncKeyID',
    'type': 'binary',
    'level': 6,
    'documentation': 'definition:- For public key algorithms, the ID of the public key that the data was encrypted with.\n'},
  0x47E7: {'name': 'ContentEncAESSettings',
    'type': 'master',
    'level': 6,
    'documentation': 'definition:- Settings describing the encryption algorithm used.\n'},
  0x47E8: {'name': 'AESSettingsCipherMode',
    'type': 'uinteger',
    'level': 7,
    'enum': {1: 'AES-CTR', 2: 'AES-CBC'},
    'documentation': 'definition:- The AES cipher mode used in the encryption.\n'},
  0x47E3: {'name': 'ContentSignature',
    'type': 'binary',
    'level': 6,
    'documentation': 'definition:- A cryptographic signature of the contents.\n'},
  0x47E4: {'name': 'ContentSigKeyID',
    'type': 'binary',
    'level': 6,
    'documentation': 'definition:- This is the ID of the private key that the data was signed with.\n'},
  0x47E5: {'name': 'ContentSigAlgo',
    'type': 'uinteger',
    'level': 6,
    'default': '0',
    'enum': {0: 'Not signed', 1: 'RSA'},
    'documentation': 'definition:- The algorithm used for the signature.\n'},
  0x47E6: {'name': 'ContentSigHashAlgo',
    'type': 'uinteger',
    'level': 6,
    'default': '0',
    'enum': {0: 'Not signed', 1: 'SHA1-160', 2: 'MD5'},
    'documentation': 'definition:- The hash algorithm used for the signature.\n'},
  0x1C53BB6B: {'name': 'Cues',
    'type': 'master',
    'level': 1,
    'documentation': 'definition:- A `Top-Level Element` to speed seeking access.  All entries are\n    local to the `Segment`.\n'},
  0xBB: {'name': 'CuePoint',
    'type': 'master',
    'level': 2,
    'documentation': 'definition:- Contains all information relative to a seek point in the `Segment`.\n'},
  0xB3: {'name': 'CueTime',
    'type': 'uinteger',
    'level': 3,
    'documentation': 'definition:- Absolute timestamp of the seek point, expressed in Segment Ticks, which are based on `TimestampScale`; see (#timestamp-ticks).\n'},
  0xB7: {'name': 'CueTrackPositions',
    'type': 'master',
    'level': 3,
    'documentation': 'definition:- Contains positions for different tracks corresponding to the timestamp.\n'},
  0xF7: {'name': 'CueTrack',
    'type': 'uinteger',
    'level': 4,
    'documentation': 'definition:- The track for which a position is given.\n'},
  0xF1: {'name': 'CueClusterPosition',
    'type': 'uinteger',
    'level': 4,
    'documentation': 'definition:- The `Segment Position` ((#segment-position)) of the `Cluster` containing the associated `Block`.\n'},
  0xF0: {'name': 'CueRelativePosition',
    'type': 'uinteger',
    'level': 4,
    'documentation': 'definition:- The relative position inside the `Cluster` of the referenced `SimpleBlock` or `BlockGroup`\nwith 0 being the first possible position for an element inside that `Cluster`.\n'},
  0xB2: {'name': 'CueDuration',
    'type': 'uinteger',
    'level': 4,
    'documentation': 'definition:- The duration of the block, expressed in Segment Ticks, which are based on `TimestampScale`; see (#timestamp-ticks).\nIf missing, the track''s `DefaultDuration` does not apply and no duration information is available in terms of the cues.\n'},
  0x5378: {'name': 'CueBlockNumber',
    'type': 'uinteger',
    'level': 4,
    'documentation': 'definition:- Number of the `Block` in the specified `Cluster`.\n'},
  0xEA: {'name': 'CueCodecState',
    'type': 'uinteger',
    'level': 4,
    'default': '0',
    'documentation': 'definition:- The `Segment Position` ((#segment-position)) of the\n    Codec State corresponding to this `Cues` element. 0 means that the\n    data is taken from the initial `TrackEntry`.\n'},
  0xDB: {'name': 'CueReference',
    'type': 'master',
    'level': 4,
    'documentation': 'definition:- The `Clusters` containing the referenced `Blocks`.\n'},
  0x96: {'name': 'CueRefTime',
    'type': 'uinteger',
    'level': 5,
    'documentation': 'definition:- Timestamp of the referenced `Block`, expressed in Segment Ticks which is based on `TimestampScale`; see (#timestamp-ticks).\n'},
  0x97: {'name': 'CueRefCluster',
    'type': 'uinteger',
    'level': 5,
    'documentation': 'definition:- The `Segment Position` of the `Cluster` containing the referenced `Block`.\n'},
  0x535F: {'name': 'CueRefNumber',
    'type': 'uinteger',
    'level': 5,
    'default': '1',
    'documentation': 'definition:- Number of the referenced `Block` of Track X in the specified `Cluster`.\n'},
  0xEB: {'name': 'CueRefCodecState',
    'type': 'uinteger',
    'level': 5,
    'default': '0',
    'documentation': 'definition:- The `Segment Position` of the Codec State corresponding to this referenced element.\n0 means that the data is taken from the initial `TrackEntry`.\n'},
  0x1941A469: {'name': 'Attachments',
    'type': 'master',
    'level': 1,
    'documentation': 'definition:- Contains attached files.\n'},
  0x61A7: {'name': 'AttachedFile',
    'type': 'master',
    'level': 2,
    'documentation': 'definition:- An attached file.\n'},
  0x467E: {'name': 'FileDescription',
    'type': 'utf-8',
    'level': 3,
    'documentation': 'definition:- A human-friendly name for the attached file.\n'},
  0x466E: {'name': 'FileName',
    'type': 'utf-8',
    'level': 3,
    'documentation': 'definition:- Filename of the attached file.\n'},
  0x4660: {'name': 'FileMediaType',
    'type': 'string',
    'level': 3,
    'documentation': 'definition:- Media type of the file following the format described in [@!RFC6838].\n'},
  0x465C: {'name': 'FileData',
    'type': 'binary',
    'level': 3,
    'documentation': 'definition:- The data of the file.\n'},
  0x46AE: {'name': 'FileUID',
    'type': 'uinteger',
    'level': 3,
    'documentation': 'definition:- UID representing the file, as random as possible.\n'},
  0x4675: {'name': 'FileReferral',
    'type': 'binary',
    'level': 3,
    'documentation': 'definition:- A binary value that a track/codec can refer to when the attachment is needed.\n'},
  0x4661: {'name': 'FileUsedStartTime',
    'type': 'uinteger',
    'level': 3,
    'documentation': 'definition:- The timestamp at which this optimized font attachment comes into context, expressed in Segment Ticks, which are based on\n    `TimestampScale`. See [@?DivXWorldFonts].\nusage notes:- This element is reserved for future use and if written **MUST** be the segment start timestamp.\n'},
  0x4662: {'name': 'FileUsedEndTime',
    'type': 'uinteger',
    'level': 3,
    'documentation': 'definition:- The timestamp at which this optimized font attachment goes out of context, expressed in Segment Ticks, which are based on\n    `TimestampScale`. See [@?DivXWorldFonts].\nusage notes:- This element is reserved for future use and if written **MUST** be the segment end timestamp.\n'},
  0x1043A770: {'name': 'Chapters',
    'type': 'master',
    'level': 1,
    'documentation': 'definition:- A system to define basic menus and partition data.\nFor more detailed information, see (#chapters).\n'},
  0x45B9: {'name': 'EditionEntry',
    'type': 'master',
    'level': 2,
    'documentation': 'definition:- Contains all information about a `Segment` edition.\n'},
  0x45BC: {'name': 'EditionUID',
    'type': 'uinteger',
    'level': 3,
    'documentation': 'definition:- A UID that identifies the edition. It''s useful for tagging an edition.\n'},
  0x45BD: {'name': 'EditionFlagHidden',
    'type': 'uinteger',
    'level': 3,
    'default': '0',
    'documentation': 'definition:- Set to 1 if an edition is hidden. Hidden editions **SHOULD NOT** be available to the user interface\n(but still be available to Control Tracks; see (#chapter-flags) on `Chapter` flags).\n'},
  0x45DB: {'name': 'EditionFlagDefault',
    'type': 'uinteger',
    'level': 3,
    'default': '0',
    'documentation': 'definition:- Set to 1 if the edition **SHOULD** be used as the default one.\n'},
  0x45DD: {'name': 'EditionFlagOrdered',
    'type': 'uinteger',
    'level': 3,
    'default': '0',
    'documentation': 'definition:- Set to 1 if the chapters can be defined multiple times and the order to play them is enforced; see (#editionflagordered).\n'},
  0x4520: {'name': 'EditionDisplay',
    'type': 'master',
    'level': 3,
    'documentation': 'definition:- Contains a possible string to use for the edition display for the given languages.\n'},
  0x4521: {'name': 'EditionString',
    'type': 'utf-8',
    'level': 4,
    'documentation': 'definition:- Contains the string to use as the edition name.\n'},
  0x45E4: {'name': 'EditionLanguageIETF',
    'type': 'string',
    'level': 4,
    'documentation': 'definition:- One language corresponding to the EditionString,\nin the form defined in [@!RFC5646]; see [@!RFC9559, Section 12] on language codes.\n'},
  0xB6: {'name': 'ChapterAtom',
    'type': 'master',
    'level': 3,
    'documentation': 'definition:- Contains the atom information to use as the chapter atom (applies to all tracks).\n'},
  0x73C4: {'name': 'ChapterUID',
    'type': 'uinteger',
    'level': 4,
    'documentation': 'definition:- A UID that identifies the `Chapter`.\n'},
  0x5654: {'name': 'ChapterStringUID',
    'type': 'utf-8',
    'level': 4,
    'documentation': 'definition:- A unique string ID that identifies the `Chapter`.\nFor example, it is used as the storage for cue identifier values [@?WebVTT].\n'},
  0x91: {'name': 'ChapterTimeStart',
    'type': 'uinteger',
    'level': 4,
    'documentation': 'definition:- Timestamp of the start of `Chapter`, expressed in Matroska Ticks -- i.e., in nanoseconds; see (#timestamp-ticks).\n'},
  0x92: {'name': 'ChapterTimeEnd',
    'type': 'uinteger',
    'level': 4,
    'documentation': 'definition:- Timestamp of the end of `Chapter` (timestamp excluded), expressed in Matroska Ticks -- i.e., in nanoseconds; see (#timestamp-ticks).\nThe value **MUST** be greater than or equal to the `ChapterTimeStart` of the same `ChapterAtom`.\nusage notes:- With the `ChapterTimeEnd` timestamp value being excluded, it **MUST** take into account the duration of\nthe last frame it includes, especially for the `ChapterAtom` using the last frames of the `Segment`.\n'},
  0x98: {'name': 'ChapterFlagHidden',
    'type': 'uinteger',
    'level': 4,
    'default': '0',
    'documentation': 'definition:- Set to 1 if a chapter is hidden.\n    Hidden chapters **SHOULD NOT** be available to the user interface\n(but still be available to Control Tracks; see (#chapterflaghidden) on `Chapter` flags).\n'},
  0x4598: {'name': 'ChapterFlagEnabled',
    'type': 'uinteger',
    'level': 4,
    'default': '1',
    'documentation': 'definition:- Set to 1 if the chapter is enabled. It can be enabled/disabled by a Control Track.\nWhen disabled, the movie **SHOULD** skip all the content between the TimeStart and TimeEnd of this chapter; see (#chapter-flags) on `Chapter` flags.\n'},
  0x6E67: {'name': 'ChapterSegmentUUID',
    'type': 'binary',
    'level': 4,
    'documentation': 'definition:- The `SegmentUUID` of another `Segment` to play during this chapter.\nusage notes:- The value **MUST NOT** be the `SegmentUUID` value of the `Segment` it belongs to.\n'},
  0x4588: {'name': 'ChapterSkipType',
    'type': 'uinteger',
    'level': 4,
    'enum': {0: 'No Skipping', 1: 'Opening Credits', 2: 'End Credits', 3: 'Recap', 4: 'Next Preview', 5: 'Preview', 6: 'Advertisement', 7: 'Intermission'},
    'documentation': 'definition:- Indicates what type of content the `ChapterAtom` contains and might be skipped.\n    It can be used to automatically skip content based on the type.\n    If a `ChapterAtom` is inside a `ChapterAtom` that has a `ChapterSkipType` set, it\n    **MUST NOT** have a `ChapterSkipType` or have a `ChapterSkipType` with the same value as it''s parent `ChapterAtom`.\nIf the `ChapterAtom` doesn''t contain a `ChapterTimeEnd`, the value of the `ChapterSkipType` is only valid until the next `ChapterAtom` with a `ChapterSkipType` value or the end of the file.\n    \n'},
  0x6EBC: {'name': 'ChapterSegmentEditionUID',
    'type': 'uinteger',
    'level': 4,
    'documentation': 'definition:- The `EditionUID` to play from the `Segment` linked in `ChapterSegmentUUID`.\nIf `ChapterSegmentEditionUID` is undeclared, then no `Edition` of the `Linked Segment` is used; see (#medium-linking) on Medium-Linking `Segments`.\n'},
  0x63C3: {'name': 'ChapterPhysicalEquiv',
    'type': 'uinteger',
    'level': 4,
    'documentation': 'definition:- Specifies the physical equivalent of this `ChapterAtom`, e.g., "DVD" (60) or "SIDE" (50);\nsee (#physical-types) for a complete list of values.\n'},
  0x8F: {'name': 'ChapterTrack',
    'type': 'master',
    'level': 4,
    'documentation': 'definition:- List of tracks on which the chapter applies. If this element is not present, all tracks apply.\n'},
  0x89: {'name': 'ChapterTrackUID',
    'type': 'uinteger',
    'level': 5,
    'documentation': 'definition:- UID of the `Track` to apply this chapter to.\nIn the absence of a control track, choosing this chapter will select the listed `Tracks` and deselect unlisted tracks.\nAbsence of this element indicates that the `Chapter` **SHOULD** be applied to any currently used `Tracks`.\n'},
  0x80: {'name': 'ChapterDisplay',
    'type': 'master',
    'level': 4,
    'documentation': 'definition:- Contains all possible strings to use for the chapter display.\n'},
  0x85: {'name': 'ChapString',
    'type': 'utf-8',
    'level': 5,
    'documentation': 'definition:- Contains the string to use as the chapter atom.\n'},
  0x437C: {'name': 'ChapLanguage',
    'type': 'string',
    'level': 5,
    'default': 'eng',
    'documentation': 'definition:- A language corresponding to the string,\nin the Matroska languages form; see (#language-codes) on language codes.\nThis element **MUST** be ignored if a `ChapLanguageBCP47` element is used within the same `ChapterDisplay` element.\n'},
  0x437D: {'name': 'ChapLanguageBCP47',
    'type': 'string',
    'level': 5,
    'documentation': 'definition:- A language corresponding to the `ChapString`,\nin the form defined in [@!RFC5646]; see (#language-codes) on language codes.\nIf a `ChapLanguageBCP47` element is used, then any `ChapLanguage` and `ChapCountry` elements used in the same `ChapterDisplay` **MUST** be ignored.\n'},
  0x437E: {'name': 'ChapCountry',
    'type': 'string',
    'level': 5,
    'documentation': 'definition:- A country corresponding to the string,\nin the Matroska countries form; see (#country-codes) on country codes.\nThis element **MUST** be ignored if a `ChapLanguageBCP47` element is used within the same `ChapterDisplay` element.\n'},
  0x6944: {'name': 'ChapProcess',
    'type': 'master',
    'level': 4,
    'documentation': 'definition:- Contains all the commands associated with the Atom.\n'},
  0x6955: {'name': 'ChapProcessCodecID',
    'type': 'uinteger',
    'level': 5,
    'default': '0',
    'enum': {0: 'Matroska Script', 1: 'DVD-menu'},
    'documentation': 'definition:- Contains the type of the codec used for processing.\n'},
  0x450D: {'name': 'ChapProcessPrivate',
    'type': 'binary',
    'level': 5,
    'documentation': 'definition:- Optional data attached to the `ChapProcessCodecID` information.\n    For `ChapProcessCodecID` = 1, it is the "DVD level" equivalent; see (#menu-features) on DVD menus.\n'},
  0x6911: {'name': 'ChapProcessCommand',
    'type': 'master',
    'level': 5,
    'documentation': 'definition:- Contains all the commands associated with the Atom.\n'},
  0x6922: {'name': 'ChapProcessTime',
    'type': 'uinteger',
    'level': 6,
    'enum': {0: 'during the whole chapter', 1: 'before starting playback', 2: 'after playback of the chapter'},
    'documentation': 'definition:- Defines when the process command **SHOULD** be handled.\n'},
  0x6933: {'name': 'ChapProcessData',
    'type': 'binary',
    'level': 6,
    'documentation': 'definition:- Contains the command information.\nThe data **SHOULD** be interpreted depending on the `ChapProcessCodecID` value. For `ChapProcessCodecID` = 1,\nthe data correspond to the binary DVD cell pre/post commands; see (#menu-features) on DVD menus.\n'},
  0x1254C367: {'name': 'Tags',
    'type': 'master',
    'level': 1,
    'documentation': 'definition:- Element containing metadata describing `Tracks`, `Editions`, `Chapters`, `Attachments`, or the `Segment` as a whole.\nA list of valid tags can be found in [@?I-D.ietf-cellar-tags].\n'},
  0x7373: {'name': 'Tag',
    'type': 'master',
    'level': 2,
    'documentation': 'definition:- A single metadata descriptor.\n'},
  0x63C0: {'name': 'Targets',
    'type': 'master',
    'level': 3,
    'documentation': 'definition:- Specifies which other elements the metadata represented by the tag value applies to.\nIf empty or omitted, then the tag value describes everything in the `Segment`.\n'},
  0x68CA: {'name': 'TargetTypeValue',
    'type': 'uinteger',
    'level': 4,
    'default': '50',
    'enum': {10: 'SHOT', 20: 'SUBTRACK / MOVEMENT / SCENE', 30: 'TRACK / SONG / CHAPTER', 40: 'PART / SESSION', 50: 'ALBUM / OPERA / CONCERT / MOVIE / EPISODE', 60: 'EDITION / ISSUE / VOLUME / OPUS / SEASON / SEQUEL', 70: 'COLLECTION'},
    'documentation': 'definition:- A number to indicate the logical level of the target.\nusage notes:- The `TargetTypeValue` values are meant to be compared.\n    Higher values **MUST** correspond to a logical level that contains the lower logical level `TargetTypeValue` values.\n'},
  0x63CA: {'name': 'TargetType',
    'type': 'string',
    'level': 4,
    'enum': {'COLLECTION': 'TargetTypeValue 70', 'EDITION': 'TargetTypeValue 60', 'ISSUE': 'TargetTypeValue 60', 'VOLUME': 'TargetTypeValue 60', 'OPUS': 'TargetTypeValue 60', 'SEASON': 'TargetTypeValue 60', 'SEQUEL': 'TargetTypeValue 60', 'ALBUM': 'TargetTypeValue 50', 'OPERA': 'TargetTypeValue 50', 'CONCERT': 'TargetTypeValue 50', 'MOVIE': 'TargetTypeValue 50', 'EPISODE': 'TargetTypeValue 50', 'PART': 'TargetTypeValue 40', 'SESSION': 'TargetTypeValue 40', 'TRACK': 'TargetTypeValue 30', 'SONG': 'TargetTypeValue 30', 'CHAPTER': 'TargetTypeValue 30', 'SUBTRACK': 'TargetTypeValue 20', 'MOVEMENT': 'TargetTypeValue 20', 'SCENE': 'TargetTypeValue 20', 'SHOT': 'TargetTypeValue 10'},
    'documentation': 'definition:- An informational string that can be used to display the logical level of the target, such as "ALBUM", "TRACK", "MOVIE", "CHAPTER", etc.\n'},
  0x63C5: {'name': 'TagTrackUID',
    'type': 'uinteger',
    'level': 4,
    'default': '0',
    'documentation': 'definition:- A UID that identifies the `Track(s)` that the tags belong to.\nusage notes:- If the value is 0 at this level, the tags apply to all tracks in the `Segment`.\nIf set to any other value, it **MUST** match the `TrackUID` value of a track found in this `Segment`.\n'},
  0x63C9: {'name': 'TagEditionUID',
    'type': 'uinteger',
    'level': 4,
    'default': '0',
    'documentation': 'definition:- A UID that identifies the `EditionEntry(s)` that the tags belong to.\nusage notes:- If the value is 0 at this level, the tags apply to all editions in the `Segment`.\nIf set to any other value, it **MUST** match the `EditionUID` value of an edition found in this `Segment`.\n'},
  0x63C4: {'name': 'TagChapterUID',
    'type': 'uinteger',
    'level': 4,
    'default': '0',
    'documentation': 'definition:- A UID that identifies the `Chapter(s)` that the tags belong to.\nusage notes:- If the value is 0 at this level, the tags apply to all chapters in the `Segment`.\nIf set to any other value, it **MUST** match the `ChapterUID` value of a chapter found in this `Segment`.\n'},
  0x63C6: {'name': 'TagAttachmentUID',
    'type': 'uinteger',
    'level': 4,
    'default': '0',
    'documentation': 'definition:- A UID that identifies the Attachment(s) that the tags belong to.\nusage notes:- If the value is 0 at this level, the tags apply to all the attachments in\n    the `Segment`.  If set to any other value, it **MUST** match\n    the `FileUID` value of an attachment found in this `Segment`.\n'},
  0x63C7: {'name': 'TagBlockAddIDValue',
    'type': 'uinteger',
    'level': 4,
    'default': '0',
    'documentation': 'definition:- A `BlockAddIDValue`that identifies the `Block Addition Mapping` that the tags belong to.\nusage notes:- If the value is 0 at this level and if the `TrackUID` value is 0 at this level,\nthe tags apply to all block addition mappings in this `Segment`.\nIf the value is 0 at this level and if the `TrackUID` value is not 0 at this level, the tags apply to all block addition mappings in the referenced `Track`.\nIf the value is not 0 at this level and if the `TrackUID` value is 0 at this level, the tags apply to all block addition mappings with this value in this `Segment`.\nIf the value is not 0 at this level and if the `TrackUID` value is not 0 at this level, the value **MUST** match the `BlockAddIDValue` value\nof a block addition mapping found in the referenced `Track`.\n\n'},
  0x67C8: {'name': 'SimpleTag',
    'type': 'master',
    'level': 3,
    'documentation': 'definition:- Contains general information about the target.\n'},
  0x45A3: {'name': 'TagName',
    'type': 'utf-8',
    'level': 4,
    'documentation': 'definition:- The name of the tag value that is going to be stored.\n'},
  0x447A: {'name': 'TagLanguage',
    'type': 'string',
    'level': 4,
    'default': 'und',
    'documentation': 'definition:- Specifies the language of the specified tag in the Matroska languages form; see (#language-codes) on language codes.\nThis element **MUST** be ignored if the `TagLanguageBCP47` element is used within the same `SimpleTag` element.\n'},
  0x447B: {'name': 'TagLanguageBCP47',
    'type': 'string',
    'level': 4,
    'documentation': 'definition:- The language used in the `TagString`,\nin the form defined in [@!RFC5646]; see (#language-codes) on language codes.\nIf this element is used, then any `TagLanguage` elements used in the same `SimpleTag` **MUST** be ignored.\n'},
  0x4484: {'name': 'TagDefault',
    'type': 'uinteger',
    'level': 4,
    'default': '1',
    'documentation': 'definition:- A boolean value to indicate if this is the default/original language to use for the given tag.\n'},
  0x44B4: {'name': 'TagDefaultBogus',
    'type': 'uinteger',
    'level': 4,
    'default': '1',
    'documentation': 'definition:- A variant of the `TagDefault` element with a bogus element ID; see (#tagdefault-element).\n'},
  0x4487: {'name': 'TagString',
    'type': 'utf-8',
    'level': 4,
    'documentation': 'definition:- The tag value.\n'},
  0x4485: {'name': 'TagBinary',
    'type': 'binary',
    'level': 4,
    'documentation': 'definition:- The tag value if it is binary. Note that this cannot be used in the same `SimpleTag` as `TagString`.\n'}
}
