"""
idlookups.py

lookup table derived from ebml and matroska specifications at:
https://github.com/ietf-wg-cellar/ebml-specification/blob/master/ebml.xml
https://github.com/ietf-wg-cellar/matroska-specification/blob/master/ebml_matroska.xml

XSLT 2.0 stylesheet was applied to above specs and output files merged by hand:

<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns="urn:ietf:rfc:8794" xmlns:matroska="urn:ietf:rfc:8794">
<xsl:output method="text" omit-xml-declaration="yes" indent="no"/>

  <xsl:template match="/">
    <xsl:text>id_table = {
</xsl:text>
    <xsl:apply-templates select="/matroska:EBMLSchema/matroska:element"/>
    <xsl:text>}</xsl:text>
  </xsl:template>

  <xsl:template match="matroska:element">
    <xsl:variable name="enum">
        <xsl:for-each select="matroska:restriction/matroska:enum">
            <xsl:value-of select="concat(@value, ': ''', replace(@label, '''', '\\'''), '''')"/>
            <xsl:if test="position() != last()">, </xsl:if>
        </xsl:for-each>
    </xsl:variable>
    <xsl:variable name="documentation">
        <xsl:for-each select="matroska:documentation">
            <xsl:value-of select="concat(@purpose, ':- ', replace(replace(., '&#10;', '\\n'), '''', ''''''), '\n')"/>
        </xsl:for-each>
    </xsl:variable>
    <xsl:value-of select="concat('  ', @id, ': {''name'': ''', @name, ''',', codepoints-to-string(10))"/>
    <xsl:value-of select="concat('    ''type'': ''', @type, ''',', codepoints-to-string(10))"/>
    <xsl:choose>
        <xsl:when test="@id eq '0xBF' or @id eq '0xEC'">
            <xsl:value-of select="concat('    ''level'': ', 7, ',', codepoints-to-string(10))"/>
        </xsl:when>
        <xsl:otherwise>
            <xsl:value-of select="concat('    ''level'': ', string-length(@path) - string-length(translate(@path, '\', '')) -1, ',', codepoints-to-string(10))"/>
        </xsl:otherwise>
    </xsl:choose>
    <xsl:if test="@default">
        <xsl:value-of select="concat('    ''default'': ''', @default, ''',', codepoints-to-string(10))"/>
    </xsl:if>
    <xsl:if test="string-length($enum) ne 0">
        <xsl:value-of select="concat('    ''enum'': {', $enum, '},', codepoints-to-string(10))"/>
    </xsl:if>
    <xsl:value-of select="concat('    ''documentation'': ''', $documentation, '''}')"/>
    <xsl:if test="position() != last()">,</xsl:if>
    <xsl:value-of select="codepoints-to-string(10)"/>
  </xsl:template>

</xsl:stylesheet>

"""


id_table = {
  0xEC: {'name': 'Void',
         'type': 'binary',
         'level': 7,
         'documentation': 'definition:- Used to void damaged data, to avoid unexpected behaviors when using damaged data. The content is discarded. Also used to reserve space in a sub-element for later use.\n'},
  0xBF: {'name': 'CRC-32',
         'type': 'binary',
         'level': 7,
         'documentation': 'definition:- The CRC is computed on all the data of the Master element it''s in. The CRC element should be the first in it''s parent master for easier reading. All level 1 elements should include a CRC-32. The CRC in use is the IEEE CRC32 Little Endian.\n'},
  0x1A45DFA3: {'name': 'EBML',
               'type': 'master',
               'level': 0,
               'documentation': 'definition:- Set the EBML characteristics of the data to follow. Each EBML document has to start with this.\n'},
  0x4286: {'name': 'EBMLVersion',
           'type': 'uinteger',
           'level': 1,
           'documentation': 'definition:- The version of EBML parser used to create the file.\n'},
  0x42F7: {'name': 'EBMLReadVersion',
           'type': 'uinteger',
           'level': 1,
           'documentation': 'definition:- The minimum EBML version a parser has to support to read this file.\n'},
  0x42F2: {'name': 'EBMLMaxIDLength',
           'type': 'uinteger',
           'level': 1,
           'default': '4',
           'documentation': 'definition:- The maximum length of the IDs you''ll find in this file (4 or less in Matroska).\n'},
  0x42F3: {'name': 'EBMLMaxSizeLength',
           'type': 'uinteger',
           'level': 1,
           'default': '8',
           'documentation': 'definition:- The maximum length of the sizes you''ll find in this file (8 or less in Matroska). This does not override the element size indicated at the beginning of an element. Elements that have an indicated size which is larger than what is allowed by EBMLMaxSizeLength shall be considered invalid.\n'},
  0x4282: {'name': 'DocType',
           'type': 'string',
           'level': 1,
           'default': 'matroska',
           'documentation': 'definition:- A string that describes the type of document that follows this EBML header. ''matroska'' in our case or ''webm'' for webm files.\n'},
  0x4287: {'name': 'DocTypeVersion',
           'type': 'uinteger',
           'level': 1,
           'documentation': 'definition:- The version of DocType interpreter used to create the file.\n'},
  0x4285: {'name': 'DocTypeReadVersion',
           'type': 'uinteger',
           'level': 1,
           'documentation': 'definition:- The minimum DocType version an interpreter has to support to read this file.\n'},
  0x1B538667: {'name': 'SignatureSlot',
               'type': 'master',
               'level': 1,
               'documentation': 'definition:- Contain signature of some (coming) elements in the stream.\n'},
  0x7E8A: {'name': 'SignatureAlgo',
           'type': 'uinteger',
           'level': 2,
           'documentation': 'definition:- Signature algorithm used (1=RSA, 2=elliptic).\n'},
  0x7E9A: {'name': 'SignatureHash',
           'type': 'uinteger',
           'level': 2,
           'documentation': 'definition:- Hash algorithm used (1=SHA1-160, 2=MD5).\n'},
  0x7EA5: {'name': 'SignaturePublicKey',
           'type': 'binary',
           'level': 2,
           'documentation': 'definition:- The public key to use with the algorithm (in the case of a PKI-based signature).\n'},
  0x7EB5: {'name': 'Signature',
           'type': 'binary',
           'level': 2,
           'documentation': 'definition:- The signature of the data (until a new.\n'},
  0x7E5B: {'name': 'SignatureElements',
           'type': 'master',
           'level': 1,
           'documentation': 'definition:- Contains elements that will be used to compute the signature.\n'},
  0x7E7B: {'name': 'SignatureElementList',
           'type': 'master',
           'level': 2,
           'documentation': 'definition:- \n      A list consists of a number of consecutive elements that represent one case where data is used in signature. Ex: Cluster|Block|BlockAdditional means that the BlockAdditional of all Blocks in all Clusters is used for encryption.\n    \n'},
  0x6532: {'name': 'SignedElement',
           'type': 'binary',
           'level': 2,
           'documentation': 'definition:- An element ID whose data will be used to compute the signature.\n'},
####################################### matroska elements ##########################################
  0x42F2: {'name': 'EBMLMaxIDLength',
    'type': 'uinteger',
    'level': 1,
    'default': '4',
    'documentation': ''},
  0x42F3: {'name': 'EBMLMaxSizeLength',
    'type': 'uinteger',
    'level': 1,
    'default': '8',
    'documentation': ''},
  0x18538067: {'name': 'Segment',
    'type': 'master',
    'level': 0,
    'documentation': 'definition:- The Root Element that contains all other Top-Level Elements (Elements defined only at Level 1).\nA Matroska file is composed of 1 Segment.\n'},
  0x114D9B74: {'name': 'SeekHead',
    'type': 'master',
    'level': 1,
    'documentation': 'definition:- Contains the Segment Position of other Top-Level Elements.\n'},
  0x4DBB: {'name': 'Seek',
    'type': 'master',
    'level': 2,
    'documentation': 'definition:- Contains a single seek entry to an EBML Element.\n'},
  0x53AB: {'name': 'SeekID',
    'type': 'binary',
    'level': 3,
    'documentation': 'definition:- The binary ID corresponding to the Element name.\n'},
  0x53AC: {'name': 'SeekPosition',
    'type': 'uinteger',
    'level': 3,
    'documentation': 'definition:- The Segment Position of the Element.\n'},
  0x1549A966: {'name': 'Info',
    'type': 'master',
    'level': 1,
    'documentation': 'definition:- Contains general information about the Segment.\n'},
  0x73A4: {'name': 'SegmentUID',
    'type': 'binary',
    'level': 2,
    'documentation': 'definition:- A randomly generated unique ID to identify the Segment amongst many others (128 bits).\nusage notes:- If the Segment is a part of a Linked Segment, then this Element is **REQUIRED**.\n'},
  0x7384: {'name': 'SegmentFilename',
    'type': 'utf-8',
    'level': 2,
    'documentation': 'definition:- A filename corresponding to this Segment.\n'},
  0x3CB923: {'name': 'PrevUID',
    'type': 'binary',
    'level': 2,
    'documentation': 'definition:- A unique ID to identify the previous Segment of a Linked Segment (128 bits).\nusage notes:- If the Segment is a part of a Linked Segment that uses Hard Linking,\nthen either the PrevUID or the NextUID Element is **REQUIRED**. If a Segment contains a PrevUID but not a NextUID,\nthen it **MAY** be considered as the last Segment of the Linked Segment. The PrevUID **MUST NOT** be equal to the SegmentUID.\n'},
  0x3C83AB: {'name': 'PrevFilename',
    'type': 'utf-8',
    'level': 2,
    'documentation': 'definition:- A filename corresponding to the file of the previous Linked Segment.\nusage notes:- Provision of the previous filename is for display convenience,\nbut PrevUID **SHOULD** be considered authoritative for identifying the previous Segment in a Linked Segment.\n'},
  0x3EB923: {'name': 'NextUID',
    'type': 'binary',
    'level': 2,
    'documentation': 'definition:- A unique ID to identify the next Segment of a Linked Segment (128 bits).\nusage notes:- If the Segment is a part of a Linked Segment that uses Hard Linking,\nthen either the PrevUID or the NextUID Element is **REQUIRED**. If a Segment contains a NextUID but not a PrevUID,\nthen it **MAY** be considered as the first Segment of the Linked Segment. The NextUID **MUST NOT** be equal to the SegmentUID.\n'},
  0x3E83BB: {'name': 'NextFilename',
    'type': 'utf-8',
    'level': 2,
    'documentation': 'definition:- A filename corresponding to the file of the next Linked Segment.\nusage notes:- Provision of the next filename is for display convenience,\nbut NextUID **SHOULD** be considered authoritative for identifying the Next Segment.\n'},
  0x4444: {'name': 'SegmentFamily',
    'type': 'binary',
    'level': 2,
    'documentation': 'definition:- A randomly generated unique ID that all Segments of a Linked Segment **MUST** share (128 bits).\nusage notes:- If the Segment Info contains a `ChapterTranslate` element, this Element is **REQUIRED**.\n'},
  0x6924: {'name': 'ChapterTranslate',
    'type': 'master',
    'level': 2,
    'documentation': 'definition:- The mapping between this `Segment` and a segment value in the given Chapter Codec.\nrationale:- Chapter Codec may need to address different segments, but they may not know of the way to identify such segment when stored in Matroska.\nThis element and its child elements add a way to map the internal segments known to the Chapter Codec to the Segment IDs in Matroska.\nThis allows remuxing a file with Chapter Codec without changing the content of the codec data, just the Segment mapping.\n'},
  0x69A5: {'name': 'ChapterTranslateID',
    'type': 'binary',
    'level': 3,
    'documentation': 'definition:- The binary value used to represent this Segment in the chapter codec data.\nThe format depends on the ChapProcessCodecID used; see (#chapprocesscodecid-element).\n'},
  0x69BF: {'name': 'ChapterTranslateCodec',
    'type': 'uinteger',
    'level': 3,
    'enum': {0: 'Matroska Script', 1: 'DVD-menu'},
    'documentation': 'definition:- This `ChapterTranslate` applies to this chapter codec of the given chapter edition(s); see (#chapprocesscodecid-element).\n'},
  0x69FC: {'name': 'ChapterTranslateEditionUID',
    'type': 'uinteger',
    'level': 3,
    'documentation': 'definition:- Specify a chapter edition UID on which this `ChapterTranslate` applies.\nusage notes:- When no `ChapterTranslateEditionUID` is specified in the `ChapterTranslate`, the `ChapterTranslate` applied to all chapter editions found in the Segment using the given `ChapterTranslateCodec`.\n'},
  0x2AD7B1: {'name': 'TimestampScale',
    'type': 'uinteger',
    'level': 2,
    'default': '1000000',
    'documentation': 'definition:- Timestamp scale in nanoseconds (1.000.000 means all timestamps in the Segment are expressed in milliseconds).\n'},
  0x4489: {'name': 'Duration',
    'type': 'float',
    'level': 2,
    'documentation': 'definition:- Duration of the Segment in nanoseconds based on TimestampScale.\n'},
  0x4461: {'name': 'DateUTC',
    'type': 'date',
    'level': 2,
    'documentation': 'definition:- The date and time that the Segment was created by the muxing application or library.\n'},
  0x7BA9: {'name': 'Title',
    'type': 'utf-8',
    'level': 2,
    'documentation': 'definition:- General name of the Segment.\n'},
  0x4D80: {'name': 'MuxingApp',
    'type': 'utf-8',
    'level': 2,
    'documentation': 'definition:- Muxing application or library (example: "libmatroska-0.4.3").\nusage notes:- Include the full name of the application or library followed by the version number.\n'},
  0x5741: {'name': 'WritingApp',
    'type': 'utf-8',
    'level': 2,
    'documentation': 'definition:- Writing application (example: "mkvmerge-0.3.3").\nusage notes:- Include the full name of the application followed by the version number.\n'},
  0x1F43B675: {'name': 'Cluster',
    'type': 'master',
    'level': 1,
    'documentation': 'definition:- The Top-Level Element containing the (monolithic) Block structure.\n'},
  0xE7: {'name': 'Timestamp',
    'type': 'uinteger',
    'level': 2,
    'documentation': 'definition:- Absolute timestamp of the cluster (based on TimestampScale).\nusage notes:- This element **SHOULD** be the first child element of the Cluster it belongs to,\nor the second if that Cluster contains a CRC-32 element ((#crc-32)).\n'},
  0x5854: {'name': 'SilentTracks',
    'type': 'master',
    'level': 2,
    'documentation': 'definition:- The list of tracks that are not used in that part of the stream.\nIt is useful when using overlay tracks on seeking or to decide what track to use.\n'},
  0x58D7: {'name': 'SilentTrackNumber',
    'type': 'uinteger',
    'level': 3,
    'documentation': 'definition:- One of the track number that are not used from now on in the stream.\nIt could change later if not specified as silent in a further Cluster.\n'},
  0xA7: {'name': 'Position',
    'type': 'uinteger',
    'level': 2,
    'documentation': 'definition:- The Segment Position of the Cluster in the Segment (0 in live streams).\nIt might help to resynchronise offset on damaged streams.\n'},
  0xAB: {'name': 'PrevSize',
    'type': 'uinteger',
    'level': 2,
    'documentation': 'definition:- Size of the previous Cluster, in octets. Can be useful for backward playing.\n'},
  0xA3: {'name': 'SimpleBlock',
    'type': 'binary',
    'level': 2,
    'documentation': 'definition:- Similar to Block, see (#block-structure), but without all the extra information,\nmostly used to reduced overhead when no extra feature is needed; see (#simpleblock-structure) on SimpleBlock Structure.\n'},
  0xA0: {'name': 'BlockGroup',
    'type': 'master',
    'level': 2,
    'documentation': 'definition:- Basic container of information containing a single Block and information specific to that Block.\n'},
  0xA1: {'name': 'Block',
    'type': 'binary',
    'level': 3,
    'documentation': 'definition:- Block containing the actual data to be rendered and a timestamp relative to the Cluster Timestamp;\nsee (#block-structure) on Block Structure.\n'},
  0xA2: {'name': 'BlockVirtual',
    'type': 'binary',
    'level': 3,
    'documentation': 'definition:- A Block with no data. It **MUST** be stored in the stream at the place the real Block would be in display order.\n\n'},
  0x75A1: {'name': 'BlockAdditions',
    'type': 'master',
    'level': 3,
    'documentation': 'definition:- Contain additional blocks to complete the main one.\nAn EBML parser that has no knowledge of the Block structure could still see and use/skip these data.\n'},
  0xA6: {'name': 'BlockMore',
    'type': 'master',
    'level': 4,
    'documentation': 'definition:- Contain the BlockAdditional and some parameters.\n'},
  0xEE: {'name': 'BlockAddID',
    'type': 'uinteger',
    'level': 5,
    'default': '1',
    'documentation': 'definition:- An ID to identify the BlockAdditional level.\nIf BlockAddIDType of the corresponding block is 0, this value is also the value of BlockAddIDType for the meaning of the content of BlockAdditional.\n'},
  0xA5: {'name': 'BlockAdditional',
    'type': 'binary',
    'level': 5,
    'documentation': 'definition:- Interpreted by the codec as it wishes (using the BlockAddID).\n'},
  0x9B: {'name': 'BlockDuration',
    'type': 'uinteger',
    'level': 3,
    'documentation': 'definition:- The duration of the Block (based on TimestampScale).\nThe BlockDuration Element can be useful at the end of a Track to define the duration of the last frame (as there is no subsequent Block available),\nor when there is a break in a track like for subtitle tracks.\n'},
  0xFA: {'name': 'ReferencePriority',
    'type': 'uinteger',
    'level': 3,
    'default': '0',
    'documentation': 'definition:- This frame is referenced and has the specified cache priority.\nIn cache only a frame of the same or higher priority can replace this frame. A value of 0 means the frame is not referenced.\n'},
  0xFB: {'name': 'ReferenceBlock',
    'type': 'integer',
    'level': 3,
    'documentation': 'definition:- A timestamp value, relative to the timestamp of the Block in this BlockGroup.\nThis is used to reference other frames necessary to decode this frame.\nThe relative value **SHOULD** correspond to a valid `Block` this `Block` depends on.\nHistorically Matroska Writer didn''t write the actual `Block(s)` this `Block` depends on, but *some* `Block` in the past.\n\nThe value "0" **MAY** also be used to signify this `Block` cannot be decoded on its own, but without knownledge of which `Block` is necessary. In this case, other `ReferenceBlock` **MUST NOT** be found in the same `BlockGroup`.\n\nIf the `BlockGroup` doesn''t have any `ReferenceBlock` element, then the `Block` it contains can be decoded without using any other `Block` data.\n'},
  0xFD: {'name': 'ReferenceVirtual',
    'type': 'integer',
    'level': 3,
    'documentation': 'definition:- The Segment Position of the data that would otherwise be in position of the virtual block.\n'},
  0xA4: {'name': 'CodecState',
    'type': 'binary',
    'level': 3,
    'documentation': 'definition:- The new codec state to use. Data interpretation is private to the codec.\nThis information **SHOULD** always be referenced by a seek entry.\n'},
  0x75A2: {'name': 'DiscardPadding',
    'type': 'integer',
    'level': 3,
    'documentation': 'definition:- Duration in nanoseconds of the silent data added to the Block\n(padding at the end of the Block for positive value, at the beginning of the Block for negative value).\nThe duration of DiscardPadding is not calculated in the duration of the TrackEntry and **SHOULD** be discarded during playback.\n'},
  0x8E: {'name': 'Slices',
    'type': 'master',
    'level': 3,
    'documentation': 'definition:- Contains slices description.\n'},
  0xE8: {'name': 'TimeSlice',
    'type': 'master',
    'level': 4,
    'documentation': 'definition:- Contains extra time information about the data contained in the Block.\nBeing able to interpret this Element is not **REQUIRED** for playback.\n'},
  0xCC: {'name': 'LaceNumber',
    'type': 'uinteger',
    'level': 5,
    'documentation': 'definition:- The reverse number of the frame in the lace (0 is the last frame, 1 is the next to last, etc).\nBeing able to interpret this Element is not **REQUIRED** for playback.\n'},
  0xCD: {'name': 'FrameNumber',
    'type': 'uinteger',
    'level': 5,
    'default': '0',
    'documentation': 'definition:- The number of the frame to generate from this lace with this delay\n(allow you to generate many frames from the same Block/Frame).\n'},
  0xCB: {'name': 'BlockAdditionID',
    'type': 'uinteger',
    'level': 5,
    'default': '0',
    'documentation': 'definition:- The ID of the BlockAdditional Element (0 is the main Block).\n'},
  0xCE: {'name': 'Delay',
    'type': 'uinteger',
    'level': 5,
    'default': '0',
    'documentation': 'definition:- The (scaled) delay to apply to the Element.\n'},
  0xCF: {'name': 'SliceDuration',
    'type': 'uinteger',
    'level': 5,
    'default': '0',
    'documentation': 'definition:- The (scaled) duration to apply to the Element.\n'},
  0xC8: {'name': 'ReferenceFrame',
    'type': 'master',
    'level': 3,
    'documentation': 'definition:- Contains information about the last reference frame. See [@?DivXTrickTrack].\n'},
  0xC9: {'name': 'ReferenceOffset',
    'type': 'uinteger',
    'level': 4,
    'documentation': 'definition:- The relative offset, in bytes, from the previous BlockGroup element for this Smooth FF/RW video track to the containing BlockGroup element. See [@?DivXTrickTrack].\n'},
  0xCA: {'name': 'ReferenceTimestamp',
    'type': 'uinteger',
    'level': 4,
    'documentation': 'definition:- The timecode of the BlockGroup pointed to by ReferenceOffset. See [@?DivXTrickTrack].\n'},
  0xAF: {'name': 'EncryptedBlock',
    'type': 'binary',
    'level': 2,
    'documentation': 'definition:- Describes a track with all Elements.\n'},
  0xD7: {'name': 'TrackNumber',
    'type': 'uinteger',
    'level': 3,
    'documentation': 'definition:- Similar to SimpleBlock, see (#simpleblock-structure),\nbut the data inside the Block are Transformed (encrypt and/or signed).\n'},
  0x1654AE6B: {'name': 'Tracks',
    'type': 'master',
    'level': 1,
    'documentation': 'definition:- A Top-Level Element of information with many tracks described.\n'},
  0xAE: {'name': 'TrackEntry',
    'type': 'master',
    'level': 3,
    'documentation': 'definition:- The track number as used in the Block Header (using more than 127 tracks is not encouraged,\nthough the design allows an unlimited number).\n'},
  0x73C5: {'name': 'TrackUID',
    'type': 'uinteger',
    'level': 3,
    'documentation': 'definition:- A unique ID to identify the Track.\n'},
  0x83: {'name': 'TrackType',
    'type': 'uinteger',
    'level': 3,
    'enum': {1: 'video', 2: 'audio', 3: 'complex', 16: 'logo', 17: 'subtitle', 18: 'buttons', 32: 'control', 33: 'metadata'},
    'documentation': 'definition:- The `TrackType` defines the type of each frame found in the Track.\nThe value **SHOULD** be stored on 1 octet.\n'},
  0xB9: {'name': 'FlagEnabled',
    'type': 'uinteger',
    'level': 3,
    'default': '1',
    'documentation': 'definition:- Set to 1 if the track is usable. It is possible to turn a not usable track into a usable track using chapter codecs or control tracks.\n'},
  0x88: {'name': 'FlagDefault',
    'type': 'uinteger',
    'level': 3,
    'default': '1',
    'documentation': 'definition:- Set if that track (audio, video or subs) **SHOULD** be eligible for automatic selection by the player; see (#default-track-selection) for more details.\n'},
  0x55AA: {'name': 'FlagForced',
    'type': 'uinteger',
    'level': 3,
    'default': '0',
    'documentation': 'definition:- Applies only to subtitles. Set if that track **SHOULD** be eligible for automatic selection by the player if it matches the user''s language preference,\neven if the user''s preferences would normally not enable subtitles with the selected audio track;\nthis can be used for tracks containing only translations of foreign-language audio or onscreen text.\nSee (#default-track-selection) for more details.\n'},
  0x55AB: {'name': 'FlagHearingImpaired',
    'type': 'uinteger',
    'level': 3,
    'documentation': 'definition:- Set to 1 if that track is suitable for users with hearing impairments, set to 0 if it is unsuitable for users with hearing impairments.\n'},
  0x55AC: {'name': 'FlagVisualImpaired',
    'type': 'uinteger',
    'level': 3,
    'documentation': 'definition:- Set to 1 if that track is suitable for users with visual impairments, set to 0 if it is unsuitable for users with visual impairments.\n'},
  0x55AD: {'name': 'FlagTextDescriptions',
    'type': 'uinteger',
    'level': 3,
    'documentation': 'definition:- Set to 1 if that track contains textual descriptions of video content, set to 0 if that track does not contain textual descriptions of video content.\n'},
  0x55AE: {'name': 'FlagOriginal',
    'type': 'uinteger',
    'level': 3,
    'documentation': 'definition:- Set to 1 if that track is in the content''s original language, set to 0 if it is a translation.\n'},
  0x55AF: {'name': 'FlagCommentary',
    'type': 'uinteger',
    'level': 3,
    'documentation': 'definition:- Set to 1 if that track contains commentary, set to 0 if it does not contain commentary.\n'},
  0x9C: {'name': 'FlagLacing',
    'type': 'uinteger',
    'level': 3,
    'default': '1',
    'documentation': 'definition:- Set to 1 if the track **MAY** contain blocks using lacing. When set to 0 all blocks **MUST** have their lacing flags set to No lacing; see (#block-lacing) on Block Lacing.\n'},
  0x6DE7: {'name': 'MinCache',
    'type': 'uinteger',
    'level': 3,
    'default': '0',
    'documentation': 'definition:- The minimum number of frames a player **SHOULD** be able to cache during playback.\nIf set to 0, the reference pseudo-cache system is not used.\n'},
  0x6DF8: {'name': 'MaxCache',
    'type': 'uinteger',
    'level': 3,
    'documentation': 'definition:- The maximum cache size necessary to store referenced frames in and the current frame.\n0 means no cache is needed.\n'},
  0x23E383: {'name': 'DefaultDuration',
    'type': 'uinteger',
    'level': 3,
    'documentation': 'definition:- Number of nanoseconds (not scaled via TimestampScale) per frame\n(frame in the Matroska sense -- one Element put into a (Simple)Block).\n'},
  0x234E7A: {'name': 'DefaultDecodedFieldDuration',
    'type': 'uinteger',
    'level': 3,
    'documentation': 'definition:- The period in nanoseconds (not scaled by TimestampScale) between two successive fields at the output of the decoding process,\nsee (#defaultdecodedfieldduration) for more information\n'},
  0x23314F: {'name': 'TrackTimestampScale',
    'type': 'float',
    'level': 3,
    'default': '0x1p+0',
    'documentation': 'definition:- DEPRECATED, DO NOT USE. The scale to apply on this track to work at normal speed in relation with other tracks\n(mostly used to adjust video speed when the audio length differs).\n'},
  0x537F: {'name': 'TrackOffset',
    'type': 'integer',
    'level': 3,
    'default': '0',
    'documentation': 'definition:- A value to add to the Block''s Timestamp.\nThis can be used to adjust the playback offset of a track.\n'},
  0x55EE: {'name': 'MaxBlockAdditionID',
    'type': 'uinteger',
    'level': 3,
    'default': '0',
    'documentation': 'definition:- The maximum value of BlockAddID ((#blockaddid-element)).\nA value 0 means there is no BlockAdditions ((#blockadditions-element)) for this track.\n'},
  0x41E4: {'name': 'BlockAdditionMapping',
    'type': 'master',
    'level': 3,
    'documentation': 'definition:- Contains elements that extend the track format, by adding content either to each frame,\nwith BlockAddID ((#blockaddid-element)), or to the track as a whole\nwith BlockAddIDExtraData.\n'},
  0x41F0: {'name': 'BlockAddIDValue',
    'type': 'uinteger',
    'level': 4,
    'documentation': 'definition:- If the track format extension needs content beside frames,\nthe value refers to the BlockAddID ((#blockaddid-element)), value being described.\nTo keep MaxBlockAdditionID as low as possible, small values **SHOULD** be used.\n'},
  0x41A4: {'name': 'BlockAddIDName',
    'type': 'string',
    'level': 4,
    'documentation': 'definition:- A human-friendly name describing the type of BlockAdditional data,\nas defined by the associated Block Additional Mapping.\n'},
  0x41E7: {'name': 'BlockAddIDType',
    'type': 'uinteger',
    'level': 4,
    'default': '0',
    'documentation': 'definition:- Stores the registered identifier of the Block Additional Mapping\nto define how the BlockAdditional data should be handled.\n'},
  0x41ED: {'name': 'BlockAddIDExtraData',
    'type': 'binary',
    'level': 4,
    'documentation': 'definition:- Extra binary data that the BlockAddIDType can use to interpret the BlockAdditional data.\nThe interpretation of the binary data depends on the BlockAddIDType value and the corresponding Block Additional Mapping.\n'},
  0x536E: {'name': 'Name',
    'type': 'utf-8',
    'level': 3,
    'documentation': 'definition:- A human-readable track name.\n'},
  0x22B59C: {'name': 'Language',
    'type': 'string',
    'level': 3,
    'default': 'eng',
    'documentation': 'definition:- Specifies the language of the track in the Matroska languages form;\nsee (#language-codes) on language codes.\nThis Element **MUST** be ignored if the LanguageIETF Element is used in the same TrackEntry.\n'},
  0x22B59D: {'name': 'LanguageIETF',
    'type': 'string',
    'level': 3,
    'documentation': 'definition:- Specifies the language of the track according to [@!BCP47]\nand using the IANA Language Subtag Registry [@!IANALangRegistry].\nIf this Element is used, then any Language Elements used in the same TrackEntry **MUST** be ignored.\n'},
  0x86: {'name': 'CodecID',
    'type': 'string',
    'level': 3,
    'documentation': 'definition:- An ID corresponding to the codec,\nsee [@!MatroskaCodec] for more info.\n'},
  0x63A2: {'name': 'CodecPrivate',
    'type': 'binary',
    'level': 3,
    'documentation': 'definition:- Private data only known to the codec.\n'},
  0x258688: {'name': 'CodecName',
    'type': 'utf-8',
    'level': 3,
    'documentation': 'definition:- A human-readable string specifying the codec.\n'},
  0x7446: {'name': 'AttachmentLink',
    'type': 'uinteger',
    'level': 3,
    'documentation': 'definition:- The UID of an attachment that is used by this codec.\nusage notes:- The value **MUST** match the `FileUID` value of an attachment found in this Segment.\n'},
  0x3A9697: {'name': 'CodecSettings',
    'type': 'utf-8',
    'level': 3,
    'documentation': 'definition:- A string describing the encoding setting used.\n'},
  0x3B4040: {'name': 'CodecInfoURL',
    'type': 'string',
    'level': 3,
    'documentation': 'definition:- A URL to find information about the codec used.\n'},
  0x26B240: {'name': 'CodecDownloadURL',
    'type': 'string',
    'level': 3,
    'documentation': 'definition:- A URL to download about the codec used.\n'},
  0xAA: {'name': 'CodecDecodeAll',
    'type': 'uinteger',
    'level': 3,
    'default': '1',
    'documentation': 'definition:- Set to 1 if the codec can decode potentially damaged data.\n'},
  0x6FAB: {'name': 'TrackOverlay',
    'type': 'uinteger',
    'level': 3,
    'documentation': 'definition:- Specify that this track is an overlay track for the Track specified (in the u-integer).\nThat means when this track has a gap, see (#silenttracks-element) on SilentTracks,\nthe overlay track **SHOULD** be used instead. The order of multiple TrackOverlay matters, the first one is the one that **SHOULD** be used.\nIf not found it **SHOULD** be the second, etc.\n'},
  0x56AA: {'name': 'CodecDelay',
    'type': 'uinteger',
    'level': 3,
    'documentation': 'definition:- CodecDelay is The codec-built-in delay in nanoseconds.\nThis value **MUST** be subtracted from each block timestamp in order to get the actual timestamp.\nThe value **SHOULD** be small so the muxing of tracks with the same actual timestamp are in the same Cluster.\n'},
  0x56BB: {'name': 'SeekPreRoll',
    'type': 'uinteger',
    'level': 3,
    'default': '0',
    'documentation': 'definition:- After a discontinuity, SeekPreRoll is the duration in nanoseconds of the data\nthe decoder **MUST** decode before the decoded data is valid.\n'},
  0x6624: {'name': 'TrackTranslate',
    'type': 'master',
    'level': 3,
    'documentation': 'definition:- The mapping between this `TrackEntry` and a track value in the given Chapter Codec.\nrationale:- Chapter Codec may need to address content in specific track, but they may not know of the way to identify tracks in Matroska.\nThis element and its child elements add a way to map the internal tracks known to the Chapter Codec to the track IDs in Matroska.\nThis allows remuxing a file with Chapter Codec without changing the content of the codec data, just the track mapping.\n'},
  0x66A5: {'name': 'TrackTranslateTrackID',
    'type': 'binary',
    'level': 4,
    'documentation': 'definition:- The binary value used to represent this `TrackEntry` in the chapter codec data.\nThe format depends on the `ChapProcessCodecID` used; see (#chapprocesscodecid-element).\n'},
  0x66BF: {'name': 'TrackTranslateCodec',
    'type': 'uinteger',
    'level': 4,
    'enum': {0: 'Matroska Script', 1: 'DVD-menu'},
    'documentation': 'definition:- This `TrackTranslate` applies to this chapter codec of the given chapter edition(s); see (#chapprocesscodecid-element).\n'},
  0x66FC: {'name': 'TrackTranslateEditionUID',
    'type': 'uinteger',
    'level': 4,
    'documentation': 'definition:- Specify a chapter edition UID on which this `TrackTranslate` applies.\nusage notes:- When no `TrackTranslateEditionUID` is specified in the `TrackTranslate`, the `TrackTranslate` applies to all chapter editions found in the Segment using the given `TrackTranslateCodec`.\n'},
  0xE0: {'name': 'Video',
    'type': 'master',
    'level': 3,
    'documentation': 'definition:- Video settings.\n'},
  0x9A: {'name': 'FlagInterlaced',
    'type': 'uinteger',
    'level': 4,
    'default': '0',
    'enum': {0: 'undetermined', 1: 'interlaced', 2: 'progressive'},
    'documentation': 'definition:- Specify whether the video frames in this track are interlaced or not.\n'},
  0x9D: {'name': 'FieldOrder',
    'type': 'uinteger',
    'level': 4,
    'default': '2',
    'enum': {0: 'progressive', 1: 'tff', 2: 'undetermined', 6: 'bff', 9: 'bff(swapped)', 14: 'tff(swapped)'},
    'documentation': 'definition:- Specify the field ordering of video frames in this track.\nusage notes:- If FlagInterlaced is not set to 1, this Element **MUST** be ignored.\n'},
  0x53B8: {'name': 'StereoMode',
    'type': 'uinteger',
    'level': 4,
    'default': '0',
    'enum': {0: 'mono', 1: 'side by side (left eye first)', 2: 'top - bottom (right eye is first)', 3: 'top - bottom (left eye is first)', 4: 'checkboard (right eye is first)', 5: 'checkboard (left eye is first)', 6: 'row interleaved (right eye is first)', 7: 'row interleaved (left eye is first)', 8: 'column interleaved (right eye is first)', 9: 'column interleaved (left eye is first)', 10: 'anaglyph (cyan/red)', 11: 'side by side (right eye first)', 12: 'anaglyph (green/magenta)', 13: 'both eyes laced in one Block (left eye is first)', 14: 'both eyes laced in one Block (right eye is first)'},
    'documentation': 'definition:- Stereo-3D video mode. There are some more details in (#multi-planar-and-3d-videos).\n'},
  0x53C0: {'name': 'AlphaMode',
    'type': 'uinteger',
    'level': 4,
    'default': '0',
    'documentation': 'definition:- Alpha Video Mode. Presence of this Element indicates that\nthe BlockAdditional Element could contain Alpha data.\n'},
  0x53B9: {'name': 'OldStereoMode',
    'type': 'uinteger',
    'level': 4,
    'enum': {0: 'mono', 1: 'right eye', 2: 'left eye', 3: 'both eyes'},
    'documentation': 'definition:- DEPRECATED, DO NOT USE. Bogus StereoMode value used in old versions of libmatroska.\n'},
  0xB0: {'name': 'PixelWidth',
    'type': 'uinteger',
    'level': 4,
    'documentation': 'definition:- Width of the encoded video frames in pixels.\n'},
  0xBA: {'name': 'PixelHeight',
    'type': 'uinteger',
    'level': 4,
    'documentation': 'definition:- Height of the encoded video frames in pixels.\n'},
  0x54AA: {'name': 'PixelCropBottom',
    'type': 'uinteger',
    'level': 4,
    'default': '0',
    'documentation': 'definition:- The number of video pixels to remove at the bottom of the image.\n'},
  0x54BB: {'name': 'PixelCropTop',
    'type': 'uinteger',
    'level': 4,
    'default': '0',
    'documentation': 'definition:- The number of video pixels to remove at the top of the image.\n'},
  0x54CC: {'name': 'PixelCropLeft',
    'type': 'uinteger',
    'level': 4,
    'default': '0',
    'documentation': 'definition:- The number of video pixels to remove on the left of the image.\n'},
  0x54DD: {'name': 'PixelCropRight',
    'type': 'uinteger',
    'level': 4,
    'default': '0',
    'documentation': 'definition:- The number of video pixels to remove on the right of the image.\n'},
  0x54B0: {'name': 'DisplayWidth',
    'type': 'uinteger',
    'level': 4,
    'documentation': 'definition:- Width of the video frames to display. Applies to the video frame after cropping (PixelCrop* Elements).\n'},
  0x54BA: {'name': 'DisplayHeight',
    'type': 'uinteger',
    'level': 4,
    'documentation': 'definition:- Height of the video frames to display. Applies to the video frame after cropping (PixelCrop* Elements).\n'},
  0x54B2: {'name': 'DisplayUnit',
    'type': 'uinteger',
    'level': 4,
    'default': '0',
    'enum': {0: 'pixels', 1: 'centimeters', 2: 'inches', 3: 'display aspect ratio', 4: 'unknown'},
    'documentation': 'definition:- How DisplayWidth & DisplayHeight are interpreted.\n'},
  0x54B3: {'name': 'AspectRatioType',
    'type': 'uinteger',
    'level': 4,
    'default': '0',
    'enum': {0: 'free resizing', 1: 'keep aspect ratio', 2: 'fixed'},
    'documentation': 'definition:- Specify the possible modifications to the aspect ratio.\n'},
  0x2EB524: {'name': 'UncompressedFourCC',
    'type': 'binary',
    'level': 4,
    'documentation': 'definition:- Specify the uncompressed pixel format used for the Track''s data as a FourCC.\nThis value is similar in scope to the biCompression value of AVI''s `BITMAPINFO` [@?AVIFormat]. See the YUV video formats [@?FourCC-YUV] and RGB video formats [@?FourCC-RGB] for common values.\nusage notes:- This Element **MUST NOT** be used if the CodecID Element of the TrackEntry is set to "V_UNCOMPRESSED".\n'},
  0x2FB523: {'name': 'GammaValue',
    'type': 'float',
    'level': 4,
    'documentation': 'definition:- Gamma Value.\n'},
  0x2383E3: {'name': 'FrameRate',
    'type': 'float',
    'level': 4,
    'documentation': 'definition:- Number of frames per second. This value is Informational only. It is intended for constant frame rate streams, and **SHOULD NOT** be used for a variable frame rate TrackEntry.\n'},
  0x55B0: {'name': 'Colour',
    'type': 'master',
    'level': 4,
    'documentation': 'definition:- Settings describing the colour format.\n'},
  0x55B1: {'name': 'MatrixCoefficients',
    'type': 'uinteger',
    'level': 5,
    'default': '2',
    'enum': {0: 'Identity', 1: 'ITU-R BT.709', 2: 'unspecified', 3: 'reserved', 4: 'US FCC 73.682', 5: 'ITU-R BT.470BG', 6: 'SMPTE 170M', 7: 'SMPTE 240M', 8: 'YCoCg', 9: 'BT2020 Non-constant Luminance', 10: 'BT2020 Constant Luminance', 11: 'SMPTE ST 2085', 12: 'Chroma-derived Non-constant Luminance', 13: 'Chroma-derived Constant Luminance', 14: 'ITU-R BT.2100-0'},
    'documentation': 'definition:- The Matrix Coefficients of the video used to derive luma and chroma values from red, green, and blue color primaries.\nFor clarity, the value and meanings for MatrixCoefficients are adopted from Table 4 of ISO/IEC 23001-8:2016 or ITU-T H.273.\n'},
  0x55B2: {'name': 'BitsPerChannel',
    'type': 'uinteger',
    'level': 5,
    'default': '0',
    'documentation': 'definition:- Number of decoded bits per channel. A value of 0 indicates that the BitsPerChannel is unspecified.\n'},
  0x55B3: {'name': 'ChromaSubsamplingHorz',
    'type': 'uinteger',
    'level': 5,
    'documentation': 'definition:- The amount of pixels to remove in the Cr and Cb channels for every pixel not removed horizontally.\nExample: For video with 4:2:0 chroma subsampling, the ChromaSubsamplingHorz **SHOULD** be set to 1.\n'},
  0x55B4: {'name': 'ChromaSubsamplingVert',
    'type': 'uinteger',
    'level': 5,
    'documentation': 'definition:- The amount of pixels to remove in the Cr and Cb channels for every pixel not removed vertically.\nExample: For video with 4:2:0 chroma subsampling, the ChromaSubsamplingVert **SHOULD** be set to 1.\n'},
  0x55B5: {'name': 'CbSubsamplingHorz',
    'type': 'uinteger',
    'level': 5,
    'documentation': 'definition:- The amount of pixels to remove in the Cb channel for every pixel not removed horizontally.\nThis is additive with ChromaSubsamplingHorz. Example: For video with 4:2:1 chroma subsampling,\nthe ChromaSubsamplingHorz **SHOULD** be set to 1 and CbSubsamplingHorz **SHOULD** be set to 1.\n'},
  0x55B6: {'name': 'CbSubsamplingVert',
    'type': 'uinteger',
    'level': 5,
    'documentation': 'definition:- The amount of pixels to remove in the Cb channel for every pixel not removed vertically.\nThis is additive with ChromaSubsamplingVert.\n'},
  0x55B7: {'name': 'ChromaSitingHorz',
    'type': 'uinteger',
    'level': 5,
    'default': '0',
    'enum': {0: 'unspecified', 1: 'left collocated', 2: 'half'},
    'documentation': 'definition:- How chroma is subsampled horizontally.\n'},
  0x55B8: {'name': 'ChromaSitingVert',
    'type': 'uinteger',
    'level': 5,
    'default': '0',
    'enum': {0: 'unspecified', 1: 'top collocated', 2: 'half'},
    'documentation': 'definition:- How chroma is subsampled vertically.\n'},
  0x55B9: {'name': 'Range',
    'type': 'uinteger',
    'level': 5,
    'default': '0',
    'enum': {0: 'unspecified', 1: 'broadcast range', 2: 'full range (no clipping)', 3: 'defined by MatrixCoefficients / TransferCharacteristics'},
    'documentation': 'definition:- Clipping of the color ranges.\n'},
  0x55BA: {'name': 'TransferCharacteristics',
    'type': 'uinteger',
    'level': 5,
    'default': '2',
    'enum': {0: 'reserved', 1: 'ITU-R BT.709', 2: 'unspecified', 3: 'reserved', 4: 'Gamma 2.2 curve - BT.470M', 5: 'Gamma 2.8 curve - BT.470BG', 6: 'SMPTE 170M', 7: 'SMPTE 240M', 8: 'Linear', 9: 'Log', 10: 'Log Sqrt', 11: 'IEC 61966-2-4', 12: 'ITU-R BT.1361 Extended Colour Gamut', 13: 'IEC 61966-2-1', 14: 'ITU-R BT.2020 10 bit', 15: 'ITU-R BT.2020 12 bit', 16: 'ITU-R BT.2100 Perceptual Quantization', 17: 'SMPTE ST 428-1', 18: 'ARIB STD-B67 (HLG)'},
    'documentation': 'definition:- The transfer characteristics of the video. For clarity,\nthe value and meanings for TransferCharacteristics are adopted from Table 3 of ISO/IEC 23091-4 or ITU-T H.273.\n'},
  0x55BB: {'name': 'Primaries',
    'type': 'uinteger',
    'level': 5,
    'default': '2',
    'enum': {0: 'reserved', 1: 'ITU-R BT.709', 2: 'unspecified', 3: 'reserved', 4: 'ITU-R BT.470M', 5: 'ITU-R BT.470BG - BT.601 625', 6: 'ITU-R BT.601 525 - SMPTE 170M', 7: 'SMPTE 240M', 8: 'FILM', 9: 'ITU-R BT.2020', 10: 'SMPTE ST 428-1', 11: 'SMPTE RP 432-2', 12: 'SMPTE EG 432-2', 22: 'EBU Tech. 3213-E - JEDEC P22 phosphors'},
    'documentation': 'definition:- The colour primaries of the video. For clarity,\nthe value and meanings for Primaries are adopted from Table 2 of ISO/IEC 23091-4 or ITU-T H.273.\n'},
  0x55BC: {'name': 'MaxCLL',
    'type': 'uinteger',
    'level': 5,
    'documentation': 'definition:- Maximum brightness of a single pixel (Maximum Content Light Level)\nin candelas per square meter (cd/m^2^).\n'},
  0x55BD: {'name': 'MaxFALL',
    'type': 'uinteger',
    'level': 5,
    'documentation': 'definition:- Maximum brightness of a single full frame (Maximum Frame-Average Light Level)\nin candelas per square meter (cd/m^2^).\n'},
  0x55D0: {'name': 'MasteringMetadata',
    'type': 'master',
    'level': 5,
    'documentation': 'definition:- SMPTE 2086 mastering data.\n'},
  0x55D1: {'name': 'PrimaryRChromaticityX',
    'type': 'float',
    'level': 6,
    'documentation': 'definition:- Red X chromaticity coordinate, as defined by CIE 1931.\n'},
  0x55D2: {'name': 'PrimaryRChromaticityY',
    'type': 'float',
    'level': 6,
    'documentation': 'definition:- Red Y chromaticity coordinate, as defined by CIE 1931.\n'},
  0x55D3: {'name': 'PrimaryGChromaticityX',
    'type': 'float',
    'level': 6,
    'documentation': 'definition:- Green X chromaticity coordinate, as defined by CIE 1931.\n'},
  0x55D4: {'name': 'PrimaryGChromaticityY',
    'type': 'float',
    'level': 6,
    'documentation': 'definition:- Green Y chromaticity coordinate, as defined by CIE 1931.\n'},
  0x55D5: {'name': 'PrimaryBChromaticityX',
    'type': 'float',
    'level': 6,
    'documentation': 'definition:- Blue X chromaticity coordinate, as defined by CIE 1931.\n'},
  0x55D6: {'name': 'PrimaryBChromaticityY',
    'type': 'float',
    'level': 6,
    'documentation': 'definition:- Blue Y chromaticity coordinate, as defined by CIE 1931.\n'},
  0x55D7: {'name': 'WhitePointChromaticityX',
    'type': 'float',
    'level': 6,
    'documentation': 'definition:- White X chromaticity coordinate, as defined by CIE 1931.\n'},
  0x55D8: {'name': 'WhitePointChromaticityY',
    'type': 'float',
    'level': 6,
    'documentation': 'definition:- White Y chromaticity coordinate, as defined by CIE 1931.\n'},
  0x55D9: {'name': 'LuminanceMax',
    'type': 'float',
    'level': 6,
    'documentation': 'definition:- Maximum luminance. Represented in candelas per square meter (cd/m^2^).\n'},
  0x55DA: {'name': 'LuminanceMin',
    'type': 'float',
    'level': 6,
    'documentation': 'definition:- Minimum luminance. Represented in candelas per square meter (cd/m^2^).\n'},
  0x7670: {'name': 'Projection',
    'type': 'master',
    'level': 4,
    'documentation': 'definition:- Describes the video projection details. Used to render spherical, VR videos or flipping videos horizontally/vertically.\n'},
  0x7671: {'name': 'ProjectionType',
    'type': 'uinteger',
    'level': 5,
    'default': '0',
    'enum': {0: 'rectangular', 1: 'equirectangular', 2: 'cubemap', 3: 'mesh'},
    'documentation': 'definition:- Describes the projection used for this video track.\n'},
  0x7672: {'name': 'ProjectionPrivate',
    'type': 'binary',
    'level': 5,
    'documentation': 'definition:- Private data that only applies to a specific projection.\n\n*  If `ProjectionType` equals 0 (Rectangular),\n     then this element must not be present.\n*  If `ProjectionType` equals 1 (Equirectangular), then this element must be present and contain the same binary data that would be stored inside\n      an ISOBMFF Equirectangular Projection Box (''equi'').\n*  If `ProjectionType` equals 2 (Cubemap), then this element must be present and contain the same binary data that would be stored\n      inside an ISOBMFF Cubemap Projection Box (''cbmp'').\n*  If `ProjectionType` equals 3 (Mesh), then this element must be present and contain the same binary data that would be stored inside\n       an ISOBMFF Mesh Projection Box (''mshp'').\nusage notes:- ISOBMFF box size and fourcc fields are not included in the binary data,\nbut the FullBox version and flag fields are. This is to avoid\nredundant framing information while preserving versioning and semantics between the two container formats.\n'},
  0x7673: {'name': 'ProjectionPoseYaw',
    'type': 'float',
    'level': 5,
    'default': '0x0p+0',
    'documentation': 'definition:- Specifies a yaw rotation to the projection.\n\nValue represents a clockwise rotation, in degrees, around the up vector. This rotation must be applied\nbefore any `ProjectionPosePitch` or `ProjectionPoseRoll` rotations.\nThe value of this element **MUST** be in the -180 to 180 degree range, both included.\n\nSetting `ProjectionPoseYaw` to 180 or -180 degrees, with the `ProjectionPoseRoll` and `ProjectionPosePitch` set to 0 degrees flips the image horizontally.\n'},
  0x7674: {'name': 'ProjectionPosePitch',
    'type': 'float',
    'level': 5,
    'default': '0x0p+0',
    'documentation': 'definition:- Specifies a pitch rotation to the projection.\n\nValue represents a counter-clockwise rotation, in degrees, around the right vector. This rotation must be applied\nafter the `ProjectionPoseYaw` rotation and before the `ProjectionPoseRoll` rotation.\nThe value of this element **MUST** be in the -90 to 90 degree range, both included.\n'},
  0x7675: {'name': 'ProjectionPoseRoll',
    'type': 'float',
    'level': 5,
    'default': '0x0p+0',
    'documentation': 'definition:- Specifies a roll rotation to the projection.\n\nValue represents a counter-clockwise rotation, in degrees, around the forward vector. This rotation must be applied\nafter the `ProjectionPoseYaw` and `ProjectionPosePitch` rotations.\nThe value of this element **MUST** be in the -180 to 180 degree range, both included.\n\nSetting `ProjectionPoseRoll` to 180 or -180 degrees, the `ProjectionPoseYaw` to 180 or -180 degrees with `ProjectionPosePitch` set to 0 degrees flips the image vertically.\n\nSetting `ProjectionPoseRoll` to 180 or -180 degrees, with the `ProjectionPoseYaw` and `ProjectionPosePitch` set to 0 degrees flips the image horizontally and vertically.\n'},
  0xE1: {'name': 'Audio',
    'type': 'master',
    'level': 3,
    'documentation': 'definition:- Audio settings.\n'},
  0xB5: {'name': 'SamplingFrequency',
    'type': 'float',
    'level': 4,
    'default': '0x1.f4p+12',
    'documentation': 'definition:- Sampling frequency in Hz.\n'},
  0x78B5: {'name': 'OutputSamplingFrequency',
    'type': 'float',
    'level': 4,
    'documentation': 'definition:- Real output sampling frequency in Hz (used for SBR techniques).\n'},
  0x9F: {'name': 'Channels',
    'type': 'uinteger',
    'level': 4,
    'default': '1',
    'documentation': 'definition:- Numbers of channels in the track.\n'},
  0x7D7B: {'name': 'ChannelPositions',
    'type': 'binary',
    'level': 4,
    'documentation': 'definition:- Table of horizontal angles for each successive channel.\n'},
  0x6264: {'name': 'BitDepth',
    'type': 'uinteger',
    'level': 4,
    'documentation': 'definition:- Bits per sample, mostly used for PCM.\n'},
  0xE2: {'name': 'TrackOperation',
    'type': 'master',
    'level': 3,
    'documentation': 'definition:- Operation that needs to be applied on tracks to create this virtual track.\nFor more details look at (#track-operation).\n'},
  0xE3: {'name': 'TrackCombinePlanes',
    'type': 'master',
    'level': 4,
    'documentation': 'definition:- Contains the list of all video plane tracks that need to be combined to create this 3D track\n'},
  0xE4: {'name': 'TrackPlane',
    'type': 'master',
    'level': 5,
    'documentation': 'definition:- Contains a video plane track that need to be combined to create this 3D track\n'},
  0xE5: {'name': 'TrackPlaneUID',
    'type': 'uinteger',
    'level': 6,
    'documentation': 'definition:- The trackUID number of the track representing the plane.\n'},
  0xE6: {'name': 'TrackPlaneType',
    'type': 'uinteger',
    'level': 6,
    'enum': {0: 'left eye', 1: 'right eye', 2: 'background'},
    'documentation': 'definition:- The kind of plane this track corresponds to.\n'},
  0xE9: {'name': 'TrackJoinBlocks',
    'type': 'master',
    'level': 4,
    'documentation': 'definition:- Contains the list of all tracks whose Blocks need to be combined to create this virtual track\n'},
  0xED: {'name': 'TrackJoinUID',
    'type': 'uinteger',
    'level': 5,
    'documentation': 'definition:- The trackUID number of a track whose blocks are used to create this virtual track.\n'},
  0xC0: {'name': 'TrickTrackUID',
    'type': 'uinteger',
    'level': 3,
    'documentation': 'definition:- The TrackUID of the Smooth FF/RW video in the paired EBML structure corresponding to this video track. See [@?DivXTrickTrack].\n'},
  0xC1: {'name': 'TrickTrackSegmentUID',
    'type': 'binary',
    'level': 3,
    'documentation': 'definition:- The SegmentUID of the Segment containing the track identified by TrickTrackUID. See [@?DivXTrickTrack].\n'},
  0xC6: {'name': 'TrickTrackFlag',
    'type': 'uinteger',
    'level': 3,
    'default': '0',
    'documentation': 'definition:- Set to 1 if this video track is a Smooth FF/RW track. If set to 1, MasterTrackUID and MasterTrackSegUID should must be present and BlockGroups for this track must contain ReferenceFrame structures.\nOtherwise, TrickTrackUID and TrickTrackSegUID must be present if this track has a corresponding Smooth FF/RW track. See [@?DivXTrickTrack].\n'},
  0xC7: {'name': 'TrickMasterTrackUID',
    'type': 'uinteger',
    'level': 3,
    'documentation': 'definition:- The TrackUID of the video track in the paired EBML structure that corresponds to this Smooth FF/RW track. See [@?DivXTrickTrack].\n'},
  0xC4: {'name': 'TrickMasterTrackSegmentUID',
    'type': 'binary',
    'level': 3,
    'documentation': 'definition:- The SegmentUID of the Segment containing the track identified by MasterTrackUID. See [@?DivXTrickTrack].\n'},
  0x6D80: {'name': 'ContentEncodings',
    'type': 'master',
    'level': 3,
    'documentation': 'definition:- Settings for several content encoding mechanisms like compression or encryption.\n'},
  0x6240: {'name': 'ContentEncoding',
    'type': 'master',
    'level': 4,
    'documentation': 'definition:- Settings for one content encoding like compression or encryption.\n'},
  0x5031: {'name': 'ContentEncodingOrder',
    'type': 'uinteger',
    'level': 5,
    'default': '0',
    'documentation': 'definition:- Tells when this modification was used during encoding/muxing starting with 0 and counting upwards.\nThe decoder/demuxer has to start with the highest order number it finds and work its way down.\nThis value has to be unique over all ContentEncodingOrder Elements in the TrackEntry that contains this ContentEncodingOrder element.\n'},
  0x5032: {'name': 'ContentEncodingScope',
    'type': 'uinteger',
    'level': 5,
    'default': '1',
    'enum': {1: 'All frame contents, excluding lacing data', 2: 'The track\'s private data', 4: 'The next ContentEncoding (next `ContentEncodingOrder`. Either the data inside `ContentCompression` and/or `ContentEncryption`)'},
    'documentation': 'definition:- A bit field that describes which Elements have been modified in this way.\nValues (big-endian) can be OR''ed.\n'},
  0x5033: {'name': 'ContentEncodingType',
    'type': 'uinteger',
    'level': 5,
    'default': '0',
    'enum': {0: 'Compression', 1: 'Encryption'},
    'documentation': 'definition:- A value describing what kind of transformation is applied.\n'},
  0x5034: {'name': 'ContentCompression',
    'type': 'master',
    'level': 5,
    'documentation': 'definition:- Settings describing the compression used.\nThis Element **MUST** be present if the value of ContentEncodingType is 0 and absent otherwise.\nEach block **MUST** be decompressable even if no previous block is available in order not to prevent seeking.\n'},
  0x4254: {'name': 'ContentCompAlgo',
    'type': 'uinteger',
    'level': 6,
    'default': '0',
    'enum': {0: 'zlib', 1: 'bzlib', 2: 'lzo1x', 3: 'Header Stripping'},
    'documentation': 'definition:- The compression algorithm used.\nusage notes:- Compression method "1" (bzlib) and "2" (lzo1x) are lacking proper documentation on the format which limits implementation possibilities.\nDue to licensing conflicts on commonly available libraries compression methods "2" (lzo1x) does not offer widespread interoperability.\nDecoding implementations **MAY** support methods "1" and "2" as possible. The use of these compression methods **SHOULD NOT** be used as a default.\n'},
  0x4255: {'name': 'ContentCompSettings',
    'type': 'binary',
    'level': 6,
    'documentation': 'definition:- Settings that might be needed by the decompressor. For Header Stripping (`ContentCompAlgo`=3),\nthe bytes that were removed from the beginning of each frames of the track.\n'},
  0x5035: {'name': 'ContentEncryption',
    'type': 'master',
    'level': 5,
    'documentation': 'definition:- Settings describing the encryption used.\nThis Element **MUST** be present if the value of `ContentEncodingType` is 1 (encryption) and **MUST** be ignored otherwise.\n'},
  0x47E1: {'name': 'ContentEncAlgo',
    'type': 'uinteger',
    'level': 6,
    'default': '0',
    'enum': {0: 'Not encrypted', 1: 'DES', 2: '3DES', 3: 'Twofish', 4: 'Blowfish', 5: 'AES'},
    'documentation': 'definition:- The encryption algorithm used.\nThe value "0" means that the contents have not been encrypted.\n'},
  0x47E2: {'name': 'ContentEncKeyID',
    'type': 'binary',
    'level': 6,
    'documentation': 'definition:- For public key algorithms this is the ID of the public key the the data was encrypted with.\n'},
  0x47E7: {'name': 'ContentEncAESSettings',
    'type': 'master',
    'level': 6,
    'documentation': 'definition:- Settings describing the encryption algorithm used.\nIf `ContentEncAlgo` != 5 this **MUST** be ignored.\n'},
  0x47E8: {'name': 'AESSettingsCipherMode',
    'type': 'uinteger',
    'level': 7,
    'enum': {1: 'AES-CTR / Counter, NIST SP 800-38A', 2: 'AES-CBC / Cipher Block Chaining, NIST SP 800-38A'},
    'documentation': 'definition:- The AES cipher mode used in the encryption.\n'},
  0x47E3: {'name': 'ContentSignature',
    'type': 'binary',
    'level': 6,
    'documentation': 'definition:- A cryptographic signature of the contents.\n'},
  0x47E4: {'name': 'ContentSigKeyID',
    'type': 'binary',
    'level': 6,
    'documentation': 'definition:- This is the ID of the private key the data was signed with.\n'},
  0x47E5: {'name': 'ContentSigAlgo',
    'type': 'uinteger',
    'level': 6,
    'default': '0',
    'enum': {0: 'Not signed', 1: 'RSA'},
    'documentation': 'definition:- The algorithm used for the signature.\n'},
  0x47E6: {'name': 'ContentSigHashAlgo',
    'type': 'uinteger',
    'level': 6,
    'default': '0',
    'enum': {0: 'Not signed', 1: 'SHA1-160', 2: 'MD5'},
    'documentation': 'definition:- The hash algorithm used for the signature.\n'},
  0x1C53BB6B: {'name': 'Cues',
    'type': 'master',
    'level': 1,
    'documentation': 'definition:- A Top-Level Element to speed seeking access.\nAll entries are local to the Segment.\n'},
  0xBB: {'name': 'CuePoint',
    'type': 'master',
    'level': 2,
    'documentation': 'definition:- Contains all information relative to a seek point in the Segment.\n'},
  0xB3: {'name': 'CueTime',
    'type': 'uinteger',
    'level': 3,
    'documentation': 'definition:- Absolute timestamp according to the Segment time base.\n'},
  0xB7: {'name': 'CueTrackPositions',
    'type': 'master',
    'level': 3,
    'documentation': 'definition:- Contain positions for different tracks corresponding to the timestamp.\n'},
  0xF7: {'name': 'CueTrack',
    'type': 'uinteger',
    'level': 4,
    'documentation': 'definition:- The track for which a position is given.\n'},
  0xF1: {'name': 'CueClusterPosition',
    'type': 'uinteger',
    'level': 4,
    'documentation': 'definition:- The Segment Position of the Cluster containing the associated Block.\n'},
  0xF0: {'name': 'CueRelativePosition',
    'type': 'uinteger',
    'level': 4,
    'documentation': 'definition:- The relative position inside the Cluster of the referenced SimpleBlock or BlockGroup\nwith 0 being the first possible position for an Element inside that Cluster.\n'},
  0xB2: {'name': 'CueDuration',
    'type': 'uinteger',
    'level': 4,
    'documentation': 'definition:- The duration of the block according to the Segment time base.\nIf missing the track''s DefaultDuration does not apply and no duration information is available in terms of the cues.\n'},
  0x5378: {'name': 'CueBlockNumber',
    'type': 'uinteger',
    'level': 4,
    'documentation': 'definition:- Number of the Block in the specified Cluster.\n'},
  0xEA: {'name': 'CueCodecState',
    'type': 'uinteger',
    'level': 4,
    'default': '0',
    'documentation': 'definition:- The Segment Position of the Codec State corresponding to this Cue Element.\n0 means that the data is taken from the initial Track Entry.\n'},
  0xDB: {'name': 'CueReference',
    'type': 'master',
    'level': 4,
    'documentation': 'definition:- The Clusters containing the referenced Blocks.\n'},
  0x96: {'name': 'CueRefTime',
    'type': 'uinteger',
    'level': 5,
    'documentation': 'definition:- Timestamp of the referenced Block.\n'},
  0x97: {'name': 'CueRefCluster',
    'type': 'uinteger',
    'level': 5,
    'documentation': 'definition:- The Segment Position of the Cluster containing the referenced Block.\n'},
  0x535F: {'name': 'CueRefNumber',
    'type': 'uinteger',
    'level': 5,
    'default': '1',
    'documentation': 'definition:- Number of the referenced Block of Track X in the specified Cluster.\n'},
  0xEB: {'name': 'CueRefCodecState',
    'type': 'uinteger',
    'level': 5,
    'default': '0',
    'documentation': 'definition:- The Segment Position of the Codec State corresponding to this referenced Element.\n0 means that the data is taken from the initial Track Entry.\n'},
  0x1941A469: {'name': 'Attachments',
    'type': 'master',
    'level': 1,
    'documentation': 'definition:- Contain attached files.\n'},
  0x61A7: {'name': 'AttachedFile',
    'type': 'master',
    'level': 2,
    'documentation': 'definition:- An attached file.\n'},
  0x467E: {'name': 'FileDescription',
    'type': 'utf-8',
    'level': 3,
    'documentation': 'definition:- A human-friendly name for the attached file.\n'},
  0x466E: {'name': 'FileName',
    'type': 'utf-8',
    'level': 3,
    'documentation': 'definition:- Filename of the attached file.\n'},
  0x4660: {'name': 'FileMimeType',
    'type': 'string',
    'level': 3,
    'documentation': 'definition:- MIME type of the file.\n'},
  0x465C: {'name': 'FileData',
    'type': 'binary',
    'level': 3,
    'documentation': 'definition:- The data of the file.\n'},
  0x46AE: {'name': 'FileUID',
    'type': 'uinteger',
    'level': 3,
    'documentation': 'definition:- Unique ID representing the file, as random as possible.\n'},
  0x4675: {'name': 'FileReferral',
    'type': 'binary',
    'level': 3,
    'documentation': 'definition:- A binary value that a track/codec can refer to when the attachment is needed.\n'},
  0x4661: {'name': 'FileUsedStartTime',
    'type': 'uinteger',
    'level': 3,
    'documentation': 'definition:- The timecode at which this optimized font attachment comes into context, based on the Segment TimecodeScale. This element is reserved for future use and if written must be the segment start time. See [@?DivXWorldFonts].\n'},
  0x4662: {'name': 'FileUsedEndTime',
    'type': 'uinteger',
    'level': 3,
    'documentation': 'definition:- The timecode at which this optimized font attachment goes out of context, based on the Segment TimecodeScale. This element is reserved for future use and if written must be the segment end time. See [@?DivXWorldFonts].\n'},
  0x1043A770: {'name': 'Chapters',
    'type': 'master',
    'level': 1,
    'documentation': 'definition:- A system to define basic menus and partition data.\nFor more detailed information, look at the Chapters explanation in (#chapters).\n'},
  0x45B9: {'name': 'EditionEntry',
    'type': 'master',
    'level': 2,
    'documentation': 'definition:- Contains all information about a Segment edition.\n'},
  0x45BC: {'name': 'EditionUID',
    'type': 'uinteger',
    'level': 3,
    'documentation': 'definition:- A unique ID to identify the edition. It''s useful for tagging an edition.\n'},
  0x45BD: {'name': 'EditionFlagHidden',
    'type': 'uinteger',
    'level': 3,
    'default': '0',
    'documentation': 'definition:- Set to 1 if an edition is hidden. Hidden editions **SHOULD NOT** be available to the user interface\n(but still to Control Tracks; see (#chapter-flags) on Chapter flags).\n'},
  0x45DB: {'name': 'EditionFlagDefault',
    'type': 'uinteger',
    'level': 3,
    'default': '0',
    'documentation': 'definition:- Set to 1 if the edition **SHOULD** be used as the default one.\n'},
  0x45DD: {'name': 'EditionFlagOrdered',
    'type': 'uinteger',
    'level': 3,
    'default': '0',
    'documentation': 'definition:- Set to 1 if the chapters can be defined multiple times and the order to play them is enforced; see (#editionflagordered).\n'},
  0xB6: {'name': 'ChapterAtom',
    'type': 'master',
    'level': 3,
    'documentation': 'definition:- Contains the atom information to use as the chapter atom (apply to all tracks).\n'},
  0x73C4: {'name': 'ChapterUID',
    'type': 'uinteger',
    'level': 4,
    'documentation': 'definition:- A unique ID to identify the Chapter.\n'},
  0x5654: {'name': 'ChapterStringUID',
    'type': 'utf-8',
    'level': 4,
    'documentation': 'definition:- A unique string ID to identify the Chapter.\nUse for WebVTT cue identifier storage [@!WebVTT].\n'},
  0x91: {'name': 'ChapterTimeStart',
    'type': 'uinteger',
    'level': 4,
    'documentation': 'definition:- Timestamp of the start of Chapter (not scaled).\n'},
  0x92: {'name': 'ChapterTimeEnd',
    'type': 'uinteger',
    'level': 4,
    'documentation': 'definition:- Timestamp of the end of Chapter (timestamp excluded, not scaled).\nThe value **MUST** be greater than or equal to the `ChapterTimeStart` of the same `ChapterAtom`.\nusage notes:- The `ChapterTimeEnd` timestamp value being excluded, it **MUST** take in account the duration of\nthe last frame it includes, especially for the `ChapterAtom` using the last frames of the `Segment`.\n'},
  0x98: {'name': 'ChapterFlagHidden',
    'type': 'uinteger',
    'level': 4,
    'default': '0',
    'documentation': 'definition:- Set to 1 if a chapter is hidden. Hidden chapters **SHOULD NOT** be available to the user interface\n(but still to Control Tracks; see (#chapterflaghidden) on Chapter flags).\n'},
  0x4598: {'name': 'ChapterFlagEnabled',
    'type': 'uinteger',
    'level': 4,
    'default': '1',
    'documentation': 'definition:- Set to 1 if the chapter is enabled. It can be enabled/disabled by a Control Track.\nWhen disabled, the movie **SHOULD** skip all the content between the TimeStart and TimeEnd of this chapter; see (#chapter-flags) on Chapter flags.\n'},
  0x6E67: {'name': 'ChapterSegmentUID',
    'type': 'binary',
    'level': 4,
    'documentation': 'definition:- The SegmentUID of another Segment to play during this chapter.\nusage notes:- The value **MUST NOT** be the `SegmentUID` value of the `Segment` it belongs to.\n'},
  0x6EBC: {'name': 'ChapterSegmentEditionUID',
    'type': 'uinteger',
    'level': 4,
    'documentation': 'definition:- The EditionUID to play from the Segment linked in ChapterSegmentUID.\nIf ChapterSegmentEditionUID is undeclared, then no Edition of the linked Segment is used; see (#medium-linking) on medium-linking Segments.\n'},
  0x63C3: {'name': 'ChapterPhysicalEquiv',
    'type': 'uinteger',
    'level': 4,
    'documentation': 'definition:- Specify the physical equivalent of this ChapterAtom like "DVD" (60) or "SIDE" (50);\nsee (#physical-types) for a complete list of values.\n'},
  0x8F: {'name': 'ChapterTrack',
    'type': 'master',
    'level': 4,
    'documentation': 'definition:- List of tracks on which the chapter applies. If this Element is not present, all tracks apply\n'},
  0x89: {'name': 'ChapterTrackUID',
    'type': 'uinteger',
    'level': 5,
    'documentation': 'definition:- UID of the Track to apply this chapter to.\nIn the absence of a control track, choosing this chapter will select the listed Tracks and deselect unlisted tracks.\nAbsence of this Element indicates that the Chapter **SHOULD** be applied to any currently used Tracks.\n'},
  0x80: {'name': 'ChapterDisplay',
    'type': 'master',
    'level': 4,
    'documentation': 'definition:- Contains all possible strings to use for the chapter display.\n'},
  0x85: {'name': 'ChapString',
    'type': 'utf-8',
    'level': 5,
    'documentation': 'definition:- Contains the string to use as the chapter atom.\n'},
  0x437C: {'name': 'ChapLanguage',
    'type': 'string',
    'level': 5,
    'default': 'eng',
    'documentation': 'definition:- A language corresponding to the string,\nin the bibliographic ISO-639-2 form [@!ISO639-2].\nThis Element **MUST** be ignored if a ChapLanguageIETF Element is used within the same ChapterDisplay Element.\n'},
  0x437D: {'name': 'ChapLanguageIETF',
    'type': 'string',
    'level': 5,
    'documentation': 'definition:- Specifies a language corresponding to the ChapString in the format defined in [@!BCP47]\nand using the IANA Language Subtag Registry [@!IANALangRegistry].\nIf a ChapLanguageIETF Element is used, then any ChapLanguage and ChapCountry Elements used in the same ChapterDisplay **MUST** be ignored.\n'},
  0x437E: {'name': 'ChapCountry',
    'type': 'string',
    'level': 5,
    'documentation': 'definition:- A country corresponding to the string, using the same 2 octets country-codes as in Internet domains [@!IANADomains] based on [@!ISO3166-1] alpha-2 codes.\nThis Element **MUST** be ignored if a ChapLanguageIETF Element is used within the same ChapterDisplay Element.\n'},
  0x6944: {'name': 'ChapProcess',
    'type': 'master',
    'level': 4,
    'documentation': 'definition:- Contains all the commands associated to the Atom.\n'},
  0x6955: {'name': 'ChapProcessCodecID',
    'type': 'uinteger',
    'level': 5,
    'default': '0',
    'documentation': 'definition:- Contains the type of the codec used for the processing.\nA value of 0 means native Matroska processing (to be defined), a value of 1 means the DVD command set is used; see (#menu-features) on DVD menus.\nMore codec IDs can be added later.\n'},
  0x450D: {'name': 'ChapProcessPrivate',
    'type': 'binary',
    'level': 5,
    'documentation': 'definition:- Some optional data attached to the ChapProcessCodecID information.\n    For ChapProcessCodecID = 1, it is the "DVD level" equivalent; see (#menu-features) on DVD menus.\n'},
  0x6911: {'name': 'ChapProcessCommand',
    'type': 'master',
    'level': 5,
    'documentation': 'definition:- Contains all the commands associated to the Atom.\n'},
  0x6922: {'name': 'ChapProcessTime',
    'type': 'uinteger',
    'level': 6,
    'enum': {0: 'during the whole chapter', 1: 'before starting playback', 2: 'after playback of the chapter'},
    'documentation': 'definition:- Defines when the process command **SHOULD** be handled\n'},
  0x6933: {'name': 'ChapProcessData',
    'type': 'binary',
    'level': 6,
    'documentation': 'definition:- Contains the command information.\nThe data **SHOULD** be interpreted depending on the ChapProcessCodecID value. For ChapProcessCodecID = 1,\nthe data correspond to the binary DVD cell pre/post commands; see (#menu-features) on DVD menus.\n'},
  0x1254C367: {'name': 'Tags',
    'type': 'master',
    'level': 1,
    'documentation': 'definition:- Element containing metadata describing Tracks, Editions, Chapters, Attachments, or the Segment as a whole.\nA list of valid tags can be found in [@!MatroskaTags].\n'},
  0x7373: {'name': 'Tag',
    'type': 'master',
    'level': 2,
    'documentation': 'definition:- A single metadata descriptor.\n'},
  0x63C0: {'name': 'Targets',
    'type': 'master',
    'level': 3,
    'documentation': 'definition:- Specifies which other elements the metadata represented by the Tag applies to.\nIf empty or not present, then the Tag describes everything in the Segment.\n'},
  0x68CA: {'name': 'TargetTypeValue',
    'type': 'uinteger',
    'level': 4,
    'default': '50',
    'enum': {70: 'COLLECTION', 60: 'EDITION / ISSUE / VOLUME / OPUS / SEASON / SEQUEL', 50: 'ALBUM / OPERA / CONCERT / MOVIE / EPISODE / CONCERT', 40: 'PART / SESSION', 30: 'TRACK / SONG / CHAPTER', 20: 'SUBTRACK / PART / MOVEMENT / SCENE', 10: 'SHOT'},
    'documentation': 'definition:- A number to indicate the logical level of the target.\n'},
  0x63CA: {'name': 'TargetType',
    'type': 'string',
    'level': 4,
    'documentation': 'definition:- An informational string that can be used to display the logical level of the target like "ALBUM", "TRACK", "MOVIE", "CHAPTER", etc\n; see Section 6.4 of [@!MatroskaTags].\n'},
  0x63C5: {'name': 'TagTrackUID',
    'type': 'uinteger',
    'level': 4,
    'default': '0',
    'documentation': 'definition:- A unique ID to identify the Track(s) the tags belong to.\nusage notes:- If the value is 0 at this level, the tags apply to all tracks in the Segment.\nIf set to any other value, it **MUST** match the `TrackUID` value of a track found in this Segment.\n'},
  0x63C9: {'name': 'TagEditionUID',
    'type': 'uinteger',
    'level': 4,
    'default': '0',
    'documentation': 'definition:- A unique ID to identify the EditionEntry(s) the tags belong to.\nusage notes:- If the value is 0 at this level, the tags apply to all editions in the Segment.\nIf set to any other value, it **MUST** match the `EditionUID` value of an edition found in this Segment.\n'},
  0x63C4: {'name': 'TagChapterUID',
    'type': 'uinteger',
    'level': 4,
    'default': '0',
    'documentation': 'definition:- A unique ID to identify the Chapter(s) the tags belong to.\nusage notes:- If the value is 0 at this level, the tags apply to all chapters in the Segment.\nIf set to any other value, it **MUST** match the `ChapterUID` value of a chapter found in this Segment.\n'},
  0x63C6: {'name': 'TagAttachmentUID',
    'type': 'uinteger',
    'level': 4,
    'default': '0',
    'documentation': 'definition:- A unique ID to identify the Attachment(s) the tags belong to.\nusage notes:- If the value is 0 at this level, the tags apply to all the attachments in the Segment.\nIf set to any other value, it **MUST** match the `FileUID` value of an attachment found in this Segment.\n'},
  0x67C8: {'name': 'SimpleTag',
    'type': 'master',
    'level': 3,
    'documentation': 'definition:- Contains general information about the target.\n'},
  0x45A3: {'name': 'TagName',
    'type': 'utf-8',
    'level': 4,
    'documentation': 'definition:- The name of the Tag that is going to be stored.\n'},
  0x447A: {'name': 'TagLanguage',
    'type': 'string',
    'level': 4,
    'default': 'und',
    'documentation': 'definition:- Specifies the language of the tag specified, in the Matroska languages form;\nsee (#language-codes) on language codes.\nThis Element **MUST** be ignored if the TagLanguageIETF Element is used within the same SimpleTag Element.\n'},
  0x447B: {'name': 'TagLanguageIETF',
    'type': 'string',
    'level': 4,
    'documentation': 'definition:- Specifies the language used in the TagString according to [@!BCP47]\nand using the IANA Language Subtag Registry [@!IANALangRegistry].\nIf this Element is used, then any TagLanguage Elements used in the same SimpleTag **MUST** be ignored.\n'},
  0x4484: {'name': 'TagDefault',
    'type': 'uinteger',
    'level': 4,
    'default': '1',
    'documentation': 'definition:- A boolean value to indicate if this is the default/original language to use for the given tag.\n'},
  0x44B4: {'name': 'TagDefaultBogus',
    'type': 'uinteger',
    'level': 4,
    'default': '1',
    'documentation': 'definition:- A variant of the TagDefault element with a bogus Element ID; see (#tagdefault-element).\n'},
  0x4487: {'name': 'TagString',
    'type': 'utf-8',
    'level': 4,
    'documentation': 'definition:- The value of the Tag.\n'},
  0x4485: {'name': 'TagBinary',
    'type': 'binary',
    'level': 4,
    'documentation': 'definition:- The values of the Tag, if it is binary. Note that this cannot be used in the same SimpleTag as TagString.\n'}
}